{'name': 'eCommerce',
    'technical_name': 'ecommerce',
    'version': '1.0.0',
    'category': 'Website',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'summary': 'Online B2C/B2B shopping.',
    'description': 'The Commerce Storefront module provides comprehensive functionality for managing store within the ERP '
                   'system. It integrates seamlessly with other core applications.',
    'icon': 'ShoppingBag',
    'url': '/admin/ecommerce',
    'depends': ['system'],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],
    'display_name': 'eCommerce',
    'command_center_section': 'Website',
    'sequence': 2,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Ecommerce Tile'}