{
    'name': 'Appointments',
    'technical_name': 'appointments',
    'version': '1.0.0',
    'category': 'Appointments',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'category': 'Appointments',
    'summary': 'Online booking, scheduling, and appointment management.',
    'description': 'The Appointments module provides comprehensive functionality for managing appointments within the ERP system. It integrates seamlessly with other core applications.',
    'icon': 'CalendarCheck',
    'url': '/admin/appointments',
    'depends': ['system'],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],

    'display_name': 'Appointments',
    'command_center_section': 'Services',
    'sequence': 6,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Appointments Tile',
}
