{'name': 'Time Off',
    'technical_name': 'hr_holidays',
    'version': '1.0.0',
    'category': 'Human Resources',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'summary': 'Leave requests and allocations.',
    'description': 'The Hr Holidays module provides comprehensive functionality for managing hr holidays within the ERP '
                   'system. It integrates seamlessly with other core applications.',
    'icon': 'CalendarOff',
    'url': '/admin/time-off',
    'depends': ['system', 'hr'],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],
    'display_name': 'Time Off',
    'command_center_section': 'Human Resources',
    'sequence': 3,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Hr Holidays Tile'}