{'name': 'Website',
    'technical_name': 'website',
    'version': '1.0.0',
    'category': 'Website',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'summary': 'The core website builder.',
    'description': 'The Website module provides comprehensive functionality for managing website within the ERP system. '
                   'It integrates seamlessly with other core applications.',
    'icon': 'Globe',
    'url': '/admin/website',
    'depends': ['system'],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],
    'display_name': 'Website',
    'command_center_section': 'Website',
    'sequence': 1,
    'has_settings': True,
    'settings_url': '/admin/settings/website',
    'settings_desc': 'Configure settings',
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Website Tile'}