{'name': 'Notifications',
    'technical_name': 'notifications',
    'version': '1.0.0',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'category': 'Technical',
    'summary': 'The background push notification and webhook engine.',
    'description': 'The Notifications module provides comprehensive functionality for managing notifications within the '
                   'ERP system. It integrates seamlessly with other core applications.',
    'icon': 'Bell',
    'url': '/admin/notifications',
    'depends': ['system'],
    'installable': True,
    'application': False,
    'featured': True,
    'screenshots': [],
    'display_name': 'Notifications',
    'sequence': 99,
    'has_settings': False,
    'ui_paradigm': 'Hidden UI (Has React Components, but no Command Center Tile)',
    'navigation_path': 'Global Header -> Bell Icon'}