{'name': 'Forum',
    'technical_name': 'forum',
    'version': '1.0.0',
    'summary': 'Community Q&A.',
    'description': 'Forum for BitGuard ERP',
    'category': 'Website',
    'author': 'BitGuard',
    'website': 'https://www.bitguard.com',
    'depends': ['core', 'system'],
    'installable': True,
    'application': True,
    'auto_install': False,
    'icon': 'MessageCircle',
    'url': '/admin/forum',
    'screenshots': [],
    'display_name': 'Forum',
    'command_center_section': 'Website',
    'sequence': 4,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Forum Tile'}