# Generated by Django 5.2.8 on 2026-06-16 20:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('record_model', models.CharField(max_length=100)),
                ('record_id', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/')),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportEngineSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('paper_format', models.CharField(default='A4', max_length=20)),
                ('margin_top', models.IntegerField(default=15)),
                ('margin_bottom', models.IntegerField(default=15)),
                ('margin_left', models.IntegerField(default=15)),
                ('margin_right', models.IntegerField(default=15)),
                ('company_header_html', models.TextField(blank=True)),
                ('company_footer_html', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(help_text="e.g., 'accounting.Invoice' or 'ecommerce.Order'", max_length=100)),
                ('html_content', models.TextField(help_text='Jinja2 or Django template syntax for the report')),
                ('css_content', models.TextField(blank=True, help_text='Custom styling for the report')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
