# Generated by Django 5.2.8 on 2026-06-19 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_analyticaccount_analyticline_billline_costcenter_and_more'),
        ('hrm', '0003_expensereport_payrollrun_payrollstructure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensereport',
            name='analytic_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.analyticaccount'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='analytic_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.analyticaccount'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='analytic_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.analyticaccount'),
        ),
    ]
