# Generated by Django 5.2.8 on 2026-07-16 20:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_payroll', '__first__'),
        ('hr_recruitment', '__first__'),
        ('hrm', '0004_expensereport_analytic_account_and_more'),
        ('tenants', '0003_tenant_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='expensereport',
            name='analytic_account',
        ),
        migrations.RemoveField(
            model_name='expensereport',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='expensereport',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='expensereport',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='job_position',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='jobposition',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='jobposition',
            name='department',
        ),
        migrations.RemoveField(
            model_name='jobposition',
            name='tenant',
        ),
        migrations.AlterField(
            model_name='employeecontract',
            name='job_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_recruitment.jobposition'),
        ),
        migrations.RemoveField(
            model_name='leaveallocation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='leaveallocation',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='leaveallocation',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='payrollperiod',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='payrollperiod',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='payrollrun',
            name='period',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='period',
        ),
        migrations.RemoveField(
            model_name='payrollrun',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='payrollrun',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='payrollstructure',
            name='components',
        ),
        migrations.RemoveField(
            model_name='payrollstructure',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='payrollstructure',
            name='tenant',
        ),
        migrations.AlterField(
            model_name='employeecontract',
            name='payroll_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_payroll.payrollstructure'),
        ),
        migrations.AlterUniqueTogether(
            name='payslip',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='analytic_account',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='payslipline',
            name='payslip',
        ),
        migrations.RemoveField(
            model_name='payslipline',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='payslipline',
            name='salary_component',
        ),
        migrations.RemoveField(
            model_name='payslipline',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='salarycomponent',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='salarycomponent',
            name='tenant',
        ),
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.department'),
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('skill_name', models.CharField(max_length=100)),
                ('skill_type', models.CharField(blank=True, max_length=50)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='0-100% proficiency')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_skills', to='hrm.employee')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReferralCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('reward_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Appraisal',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='ExpenseReport',
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
        migrations.DeleteModel(
            name='JobPosition',
        ),
        migrations.DeleteModel(
            name='LeaveAllocation',
        ),
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
        migrations.DeleteModel(
            name='PayrollPeriod',
        ),
        migrations.DeleteModel(
            name='PayrollRun',
        ),
        migrations.DeleteModel(
            name='PayrollStructure',
        ),
        migrations.DeleteModel(
            name='PaySlip',
        ),
        migrations.DeleteModel(
            name='PaySlipLine',
        ),
        migrations.DeleteModel(
            name='SalaryComponent',
        ),
    ]
