{'name': 'Helpdesk',
    'technical_name': 'helpdesk',
    'version': '1.0.0',
    'category': 'Helpdesk',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'summary': 'Ticketing and SLA management.',
    'description': 'The IT Service Desk module provides comprehensive functionality for managing helpdesk within the ERP '
                   'system. It integrates seamlessly with other core applications.',
    'icon': 'LifeBuoy',
    'url': '/admin/helpdesk',
    'depends': ['system'],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],
    'display_name': 'Helpdesk',
    'command_center_section': 'Services',
    'sequence': 4,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Helpdesk Tile'}