{'name': 'Subscriptions',
    'technical_name': 'subscriptions',
    'version': '1.0.0',
    'category': 'Sales',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'summary': 'Recurring billing and MRR.',
    'description': 'The Billing module provides comprehensive functionality for managing billing within the ERP system. '
                   'It integrates seamlessly with other core applications.',
    'icon': 'Repeat',
    'url': '/admin/subscriptions',
    'depends': ['system', 'accounting'],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],
    'display_name': 'Subscriptions',
    'command_center_section': 'Sales',
    'sequence': 4,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Subscriptions Tile'}