# Generated by Django 5.2.8 on 2026-08-20 13:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(help_text="e.g. 'Customer Support Agent'", max_length=100)),
                ('role', models.CharField(help_text="e.g. 'helpdesk', 'sales'", max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('system_prompt', models.TextField(help_text='The core instructions for the AI to follow.')),
                ('allowed_tools', models.JSONField(default=list, help_text="e.g. ['read_ticket', 'escalate']")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'AI Agent Profile',
                'verbose_name_plural': 'AI Agent Profiles',
                'db_table': 'ai_agent_profile',
            },
        ),
        migrations.CreateModel(
            name='AgentRunLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('triggered_by_model', models.CharField(blank=True, max_length=100)),
                ('triggered_by_id', models.CharField(blank=True, max_length=50)),
                ('thoughts', models.TextField(blank=True)),
                ('actions_taken', models.JSONField(default=list)),
                ('status', models.CharField(default='success', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_agent.agentprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Agent Run Log',
                'db_table': 'ai_agent_run_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
