# Generated by Django 5.2.8 on 2026-09-01 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrunlog',
            name='duration_ms',
            field=models.IntegerField(default=0, help_text='Total execution time in milliseconds.'),
        ),
        migrations.AddField(
            model_name='agentrunlog',
            name='final_output',
            field=models.TextField(blank=True, help_text="The agent's final answer to the user."),
        ),
        migrations.AddField(
            model_name='agentrunlog',
            name='tokens_used',
            field=models.IntegerField(default=0, help_text='Total tokens consumed in this run.'),
        ),
        migrations.AddField(
            model_name='agentrunlog',
            name='triggered_by',
            field=models.CharField(choices=[('user', 'User'), ('webhook', 'Webhook'), ('schedule', 'Schedule')], default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='agentrunlog',
            name='user_input',
            field=models.TextField(blank=True, help_text='The original prompt that triggered the run.'),
        ),
        migrations.AlterField(
            model_name='agentrunlog',
            name='actions_taken',
            field=models.JSONField(default=list, help_text='Tool calls made during the run.'),
        ),
        migrations.AlterField(
            model_name='agentrunlog',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_logs', to='ai_agent.agentprofile'),
        ),
        migrations.AlterField(
            model_name='agentrunlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('escalated', 'Escalated')], default='success', max_length=20),
        ),
        migrations.AlterField(
            model_name='agentrunlog',
            name='thoughts',
            field=models.TextField(blank=True, help_text='The step-by-step ReAct reasoning chain.'),
        ),
    ]
