# Generated by Django 5.2.8 on 2026-05-22 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsm', '0004_serviceitem_servicerequest'),
        ('store', '0005_product_expense_account_product_income_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='linked_product',
            field=models.ForeignKey(blank=True, help_text='Link to Master Catalog for billable tickets', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itsm_services', to='store.product'),
        ),
    ]
