{'icon': 'PenTool',
    'name': 'Sign',
    'version': '1.0',
    'category': 'Sign',
    'summary': 'eSignature requests.',
    'description': 'BitGuard Sign module.',
    'depends': ['core'],
    'url': '/admin/sign',
    'installable': True,
    'application': True,
    'featured': False,
    'display_name': 'Sign',
    'command_center_section': 'Accounting',
    'sequence': 260,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Sign Tile'    'has_portal': True,
    'portal_url': '/portal/contracts',
    'portal_label': 'Contracts',
}
