{'name': 'Fleet',
    'technical_name': 'fleet',
    'version': '1.0.0',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'category': 'Fleet',
    'summary': 'Company vehicle management.',
    'description': 'The Fleet module provides comprehensive functionality for managing fleet within the ERP system. It '
                   'integrates seamlessly with other core applications.',
    'icon': 'Truck',
    'url': '/admin/fleet',
    'depends': ['system'],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],
    'display_name': 'Fleet',
    'command_center_section': 'Human Resources',
    'sequence': 10,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Fleet Tile'}