"""
BitGuard Master API Router
===========================
This file has ZERO hardcoded knowledge of any app name, file path,
or whether a module is an 'app' or an 'integration'.

It simply reads the Global Registry that every app populates during
Django's boot cycle (via AppConfig.ready()) and builds the URL
configuration from it.

To add a new module's API routes, do NOT edit this file.
Instead, register your routes in your module's `apps.py`:

    class MyNewAppConfig(AppConfig):
        def ready(self):
            from apps.core.api.registry import register
            register('my_new_app/', 'apps.my_new_app.api.urls')

Architecture Rule #5 — Registry-Driven Plug-and-Play (Backend Global Registry Pattern)
"""
from django.urls import path, include
from apps.core.api.registry import get_registered_routes

# The master router reads the registry. Nothing else.
# Apps register themselves in their own apps.py ready() method.
urlpatterns = [
    path(route['prefix'], include(route['module']))
    for route in get_registered_routes()
]

