{'name': 'Amazon Connector',
    'technical_name': 'amazon',
    'version': '1.0.0',
    'category': 'Sales',
    'author': 'BitGuard',
    'summary': 'Amazon Connector module',
    'description': 'Core functionality for Amazon Connector',
    'icon': 'Box',
    'url': '/admin/amazon',
    'depends': ['system'],
    'installable': True,
    'application': True,
    'command_center_section': 'Sales',
    'sequence': 6}