# Generated by Django 5.2.8 on 2026-08-19 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutomatedAction',
        ),
    ]
