# Generated by Django 5.2.8 on 2026-09-22 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_integrationkey_delete_apikey'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='systemsetting',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='webhookendpoint',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='webhookendpoint',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='DatabaseBackup',
        ),
        migrations.DeleteModel(
            name='SystemSetting',
        ),
        migrations.DeleteModel(
            name='WebhookEndpoint',
        ),
    ]
