# Generated by Django 5.2.8 on 2026-08-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_delete_automatedaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='installedmodule',
            name='license',
            field=models.CharField(blank=True, default='LGPL-3', max_length=100),
        ),
        migrations.AddField(
            model_name='installedmodule',
            name='website',
            field=models.URLField(blank=True, help_text='App creator website', max_length=255),
        ),
    ]
