# Generated by Django 5.2.8 on 2026-08-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_installedmodule_license_installedmodule_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='installedmodule',
            name='command_center_order',
            field=models.IntegerField(default=99, help_text='Order within the section'),
        ),
        migrations.AddField(
            model_name='installedmodule',
            name='command_center_section',
            field=models.CharField(blank=True, help_text='Pillar grouping in Command Center (e.g. Finance, Sales, HR)', max_length=100),
        ),
        migrations.AddField(
            model_name='installedmodule',
            name='display_name',
            field=models.CharField(blank=True, help_text='Name shown in Command Center tile', max_length=100),
        ),
    ]
