# Generated by Django 5.2.8 on 2026-08-31 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_add_display_name_section_to_module'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installedmodule',
            old_name='command_center_order',
            new_name='sequence',
        ),
    ]
