# Generated by Django 5.2.8 on 2026-09-29 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="currency",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="currency",
            name="tenant",
        ),
    ]
