# Generated by Django 5.2.8 on 2026-09-29 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_remove_currency_created_by_remove_currency_tenant"),
        ("core", "0006_currency_alter_company_default_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchangerate",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exchange_rates",
                to="core.currency",
            ),
        ),
        migrations.AlterField(
            model_name="accountjournal",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.currency",
            ),
        ),
        migrations.DeleteModel(
            name="Currency",
        ),
    ]
