# Generated by Django 5.2.8 on 2026-06-19 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_analyticaccount_analyticline_billline_costcenter_and_more'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbill',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_bills', to='purchase.purchaseorder'),
        ),
        migrations.AddField(
            model_name='vendorbill',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_bills', to='purchase.vendor'),
        ),
    ]
