{'name': 'Manufacturing',
    'technical_name': 'mrp',
    'version': '1.0.0',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'category': 'Manufacturing',
    'summary': 'BOMs, routing, and work orders.',
    'description': 'The Manufacturing module provides comprehensive functionality for managing mrp within the ERP system. '
                   'It integrates seamlessly with other core applications.',
    'icon': 'Wrench',
    'url': '/admin/mrp',
    'depends': ['system', 'stock'],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],
    'display_name': 'Manufacturing',
    'command_center_section': 'Manufacturing',
    'sequence': 1,
    'has_settings': True,
    'settings_url': '/admin/settings/mrp',
    'settings_desc': 'Configure settings',
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Mrp Tile'}