# Generated by Django 5.2.8 on 2026-08-15 20:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.CharField(choices=[('system', 'System'), ('crm', 'CRM'), ('erp', 'ERP'), ('soc', 'SOC'), ('ecommerce', 'ecommerce'), ('billing', 'Billing'), ('hrm', 'HRM'), ('services', 'Services'), ('approvals', 'Approvals'), ('projects', 'Projects')], default='system', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('delivered_in_app', models.BooleanField(default=True)),
                ('delivered_email', models.BooleanField(default=False)),
                ('delivered_sms', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.CharField(choices=[('system', 'System'), ('crm', 'CRM'), ('erp', 'ERP'), ('soc', 'SOC'), ('ecommerce', 'ecommerce'), ('billing', 'Billing'), ('hrm', 'HRM'), ('services', 'Services'), ('approvals', 'Approvals'), ('projects', 'Projects')], max_length=20)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
