# Generated by Django 5.2.8 on 2026-07-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('system', 'System'), ('crm', 'CRM'), ('erp', 'ERP'), ('soc', 'SOC'), ('ecommerce', 'ecommerce'), ('billing', 'Billing'), ('hrm', 'HRM'), ('services', 'Services'), ('approvals', 'Approvals'), ('projects', 'Projects')], default='system', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='type',
            field=models.CharField(choices=[('system', 'System'), ('crm', 'CRM'), ('erp', 'ERP'), ('soc', 'SOC'), ('ecommerce', 'ecommerce'), ('billing', 'Billing'), ('hrm', 'HRM'), ('services', 'Services'), ('approvals', 'Approvals'), ('projects', 'Projects')], max_length=20),
        ),
    ]
