# Generated by Django 5.2.8 on 2026-05-23 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_phase4_polish'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='delivered_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='delivered_in_app',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='delivered_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('system', 'System'), ('crm', 'CRM'), ('erp', 'ERP'), ('soc', 'SOC'), ('store', 'Store'), ('billing', 'Billing'), ('hrm', 'HRM'), ('itsm', 'ITSM'), ('approvals', 'Approvals'), ('projects', 'Projects')], default='system', max_length=20),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('system', 'System'), ('crm', 'CRM'), ('erp', 'ERP'), ('soc', 'SOC'), ('store', 'Store'), ('billing', 'Billing'), ('hrm', 'HRM'), ('itsm', 'ITSM'), ('approvals', 'Approvals'), ('projects', 'Projects')], max_length=20)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'type')},
            },
        ),
    ]
