{
    'name': 'Automation',
    'technical_name': 'automation',
    'version': '1.0',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'category': 'Technical',
    'summary': 'Rules and automations engine',
    'description': 'Core engine for evaluating and running automated actions.',
    'icon': 'Zap',
    'url': '/admin/automation',
    'depends': ['core', 'system'],
    'installable': True,
    'application': False,
    'featured': True,
    'screenshots': [],

    'display_name': 'Automation',
        'sequence': 99,
    'has_settings': False,
    'ui_paradigm': 'Headless Core (Pure Python Backend, No React UI)',
    'navigation_path': 'Command Center -> Settings -> Automation',
}
