{'name': 'Security Operations Center',
    'technical_name': 'soc',
    'version': '1.0.0',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'category': 'Security',
    'summary': 'Threat monitoring, audit logs, and AI security agents.',
    'description': 'The Security Operations module provides comprehensive functionality for managing soc within the ERP '
                   'system. It integrates seamlessly with other core applications.',
    'icon': 'ShieldAlert',
    'url': '/admin/soc',
    'depends': ['system'],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],
    'display_name': 'SOC',
    'command_center_section': 'Administration',
    'sequence': 3,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Soc Tile'}