{'name': 'System',
    'technical_name': 'system',
    'version': '1.0.0',
    'category': 'Administration',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'summary': 'System registries and global settings structure.',
    'description': 'The Settings module provides comprehensive functionality for managing base setup within the ERP '
                   'system. It integrates seamlessly with other core applications.',
    'icon': 'Settings',
    'url': '/admin/settings',
    'depends': [],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],
    'display_name': 'Settings',
    'command_center_section': 'Administration',
    'sequence': 1,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Settings Tile'}