{'name': 'Employees',
    'technical_name': 'hr',
    'version': '1.0.0',
    'category': 'Human Resources',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'summary': 'The core employee directory.',
    'description': 'The Human Capital module provides comprehensive functionality for managing hr within the ERP system. '
                   'It integrates seamlessly with other core applications.',
    'icon': 'UserCheck',
    'url': '/admin/hr',
    'depends': ['system'],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],
    'display_name': 'Employees',
    'command_center_section': 'Human Resources',
    'sequence': 1,
    'has_settings': True,
    'settings_url': '/admin/settings/hr',
    'settings_desc': 'Configure settings',
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Hr Tile'}