# Generated by Django 5.2.8 on 2026-02-04 10:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('risk_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=50)),
                ('connected_users', models.IntegerField(default=0)),
                ('last_scan', models.DateTimeField(auto_now=True)),
                ('sanctioned', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmailThreat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=254)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('threat_type', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=50)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='blocked', max_length=50)),
                ('quarantined', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('ipv4', 'IPv4 Address'), ('domain', 'Domain Name'), ('url', 'URL'), ('file_hash', 'File Hash (SHA256/MD5)'), ('email', 'Email Address')], max_length=50)),
                ('source', models.CharField(default='Internal', max_length=100)),
                ('confidence', models.IntegerField(default=50, help_text='0-100 Confidence Score')),
                ('tlp', models.CharField(choices=[('RED', 'TLP:RED'), ('AMBER', 'TLP:AMBER'), ('GREEN', 'TLP:GREEN'), ('CLEAR', 'TLP:CLEAR')], default='AMBER', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ip', models.GenericIPAddressField()),
                ('destination_ip', models.GenericIPAddressField()),
                ('protocol', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RemediationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_taken', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('automated', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('informational', 'Informational')], max_length=50)),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='new', max_length=50)),
                ('score', models.IntegerField(default=0, help_text='Risk Score (0-100)')),
                ('source', models.CharField(default='SIEM', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mitre_tactic', models.CharField(blank=True, help_text='e.g., Initial Access', max_length=100)),
                ('mitre_technique', models.CharField(blank=True, help_text='e.g., T1056', max_length=100)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(default='medium', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ignored', 'Ignored'), ('resolved', 'Resolved')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(max_length=50)),
                ('status', models.CharField(default='open', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('playbook_logs', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(help_text='e.g., CVE-2023-1234', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=50)),
                ('cvss_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('patched', 'Patched'), ('accepted_risk', 'Accepted Risk')], default='open', max_length=50)),
                ('first_detected', models.DateTimeField(auto_now_add=True)),
                ('last_detected', models.DateTimeField(auto_now=True)),
                ('remediation_plan', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Hostname or Resource Name', max_length=200)),
                ('asset_type', models.CharField(choices=[('workstation', 'Workstation'), ('server', 'Server'), ('cloud_instance', 'Cloud Instance'), ('network_device', 'Network Device'), ('iot', 'IoT Device'), ('mobile', 'Mobile Device')], default='workstation', max_length=50)),
                ('criticality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('mission_critical', 'Mission Critical')], default='medium', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance'), ('isolated', 'Isolated'), ('compromised', 'Compromised')], default='active', max_length=50)),
                ('risk_score', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('os_version', models.CharField(blank=True, max_length=100)),
                ('agent_version', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, help_text='Physical or Logical Location', max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
