# Generated by Django 5.2.8 on 2026-02-04 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('security', '0001_initial'),
        ('tenants', '0002_remotesession_workspace_systemmonitor_healthmetric_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='tenants.workspace'),
        ),
        migrations.AddField(
            model_name='cloudapp',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cloud_apps', to='tenants.workspace'),
        ),
        migrations.AddField(
            model_name='emailthreat',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_threats', to='tenants.workspace'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='tenants.workspace'),
        ),
        migrations.AddField(
            model_name='networkevent',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='network_events', to='tenants.workspace'),
        ),
        migrations.AddField(
            model_name='remediationaction',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='affected_assets',
            field=models.ManyToManyField(blank=True, related_name='alerts', to='security.asset'),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='related_indicators',
            field=models.ManyToManyField(blank=True, related_name='alerts', to='security.indicator'),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_alerts', to='tenants.workspace'),
        ),
        migrations.AddField(
            model_name='securitygap',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_gaps', to='tenants.workspace'),
        ),
        migrations.AddField(
            model_name='securityincident',
            name='alerts',
            field=models.ManyToManyField(blank=True, related_name='incidents', to='security.securityalert'),
        ),
        migrations.AddField(
            model_name='securityincident',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityincident',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_incidents', to='tenants.workspace'),
        ),
        migrations.AddField(
            model_name='remediationaction',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='security.securityincident'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='affected_assets',
            field=models.ManyToManyField(related_name='vulnerabilities', to='security.asset'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='tenants.workspace'),
        ),
    ]
