{'name': 'CRM',
    'technical_name': 'crm',
    'version': '1.0.0',
    'category': 'CRM',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'summary': 'Lead and pipeline tracking.',
    'description': 'The Sales & CRM module provides comprehensive functionality for managing crm within the ERP system. '
                   'It integrates seamlessly with other core applications.',
    'icon': 'Users',
    'url': '/admin/crm',
    'depends': ['system'],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],
    'display_name': 'CRM',
    'command_center_section': 'Sales',
    'sequence': 2,
    'has_settings': True,
    'settings_url': '/admin/settings/crm',
    'settings_desc': 'Configure settings',
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Crm Tile'}