{'name': 'Auth',
    'technical_name': 'auth',
    'version': '1.0.0',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'category': 'Technical',
    'summary': 'Security gateways, JWT, and login logic.',
    'description': 'The Auth module provides comprehensive functionality for managing auth within the ERP system. It '
                   'integrates seamlessly with other core applications.',
    'icon': 'Key',
    'url': '/admin/auth',
    'depends': ['system'],
    'installable': True,
    'application': False,
    'featured': True,
    'screenshots': [],
    'display_name': 'Authentication',
    'sequence': 999,
    'has_settings': False,
    'ui_paradigm': 'Hidden UI (Has React Components, but no Command Center Tile)',
    'navigation_path': 'Root Gateway -> /login'}