{'name': 'Procurement',
    'odoo_equivalent': 'Purchase',
    'technical_name': 'procurement',
    'version': '1.0.0',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'category': 'Purchase',
    'summary': 'Vendor RFQs and POs.',
    'description': 'The Purchase module provides comprehensive functionality for managing purchase within the ERP system. '
                   'It integrates seamlessly with other core applications.',
    'icon': 'ShoppingCart',
    'url': '/admin/procurement',
    'depends': ['system', 'accounting'],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],
    'display_name': 'Procurement',
    'command_center_section': 'Inventory',
    'sequence': 320,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Purchase Tile'    'has_portal': True,
    'portal_url': '/portal/procurement',
    'portal_label': 'Procurements',
}
