{'name': 'Quality',
    'odoo_equivalent': 'Quality Control',
    'technical_name': 'quality',
    'version': '1.0.0',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'category': 'Quality',
    'summary': 'Inspections and quality alerts.',
    'description': 'The Quality Control module provides comprehensive functionality for managing quality control within '
                   'the ERP system. It integrates seamlessly with other core applications.',
    'icon': 'CheckSquare',
    'url': '/admin/quality',
    'depends': ['system'],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],
    'display_name': 'Quality',
    'command_center_section': 'Manufacturing',
    'sequence': 440,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Quality Control Tile'}