{'name': 'PLM',
    'technical_name': 'mrp_plm',
    'version': '1.0.0',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'category': 'Manufacturing',
    'summary': 'Engineering change orders and versioning.',
    'description': 'The Mrp Plm module provides comprehensive functionality for managing mrp plm within the ERP system. '
                   'It integrates seamlessly with other core applications.',
    'icon': 'GitBranch',
    'url': '/admin/mrp-plm',
    'depends': ['system'],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],
    'display_name': 'PLM',
    'command_center_section': 'Manufacturing',
    'sequence': 3,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Mrp Plm Tile'}