# Generated by Django 5.2.8 on 2026-09-30 17:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("base", "0006_currency_alter_company_default_currency"),
        ("tenants", "0003_remove_tenant_city_remove_tenant_country_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "object_id",
                    models.CharField(max_length=255, verbose_name="Record ID"),
                ),
                ("field_name", models.CharField(max_length=100, verbose_name="Field")),
                (
                    "field_label",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Field Label"
                    ),
                ),
                (
                    "old_value",
                    models.TextField(blank=True, verbose_name="Previous Value"),
                ),
                ("new_value", models.TextField(blank=True, verbose_name="New Value")),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="field_changes_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Changed By",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_histories",
                        to="contenttypes.contenttype",
                        verbose_name="Record Type",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Change Log",
                "verbose_name_plural": "Field Change Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="FieldChangeLog",
        ),
    ]
