# Generated by Django 6.0.9 on 2026-10-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_installedmodule_has_settings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordactivity',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='recordactivity',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='recordactivity',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='recordactivity',
            name='tenant',
        ),
        migrations.AlterUniqueTogether(
            name='recordfollower',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='recordfollower',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='recordfollower',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='recordfollower',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='recordfollower',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recordmessage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='recordmessage',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='recordmessage',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='recordmessage',
            name='tenant',
        ),
        migrations.AlterUniqueTogether(
            name='scheduledaction',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='scheduledaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='scheduledaction',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='systemeventlog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='systemeventlog',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='systemeventlog',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='translation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='language',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='tenant',
        ),
        migrations.AddField(
            model_name='installedmodule',
            name='has_portal',
            field=models.BooleanField(default=False, help_text='Does this module expose a customer portal page?'),
        ),
        migrations.AddField(
            model_name='installedmodule',
            name='portal_label',
            field=models.CharField(blank=True, help_text='e.g. My Leads', max_length=255),
        ),
        migrations.AddField(
            model_name='installedmodule',
            name='portal_url',
            field=models.CharField(blank=True, help_text='e.g. /portal/leads', max_length=255),
        ),
        migrations.DeleteModel(
            name='FieldHistory',
        ),
        migrations.DeleteModel(
            name='RecordActivity',
        ),
        migrations.DeleteModel(
            name='RecordFollower',
        ),
        migrations.DeleteModel(
            name='RecordMessage',
        ),
        migrations.DeleteModel(
            name='ScheduledAction',
        ),
        migrations.DeleteModel(
            name='SystemEventLog',
        ),
        migrations.DeleteModel(
            name='Translation',
        ),
    ]
