# Generated by Django 5.2.8 on 2026-07-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='role',
            name='category',
            field=models.CharField(blank=True, default='', help_text='e.g., Sales, Accounting, Human Resources', max_length=100),
        ),
        migrations.AddField(
            model_name='role',
            name='implied_ids',
            field=models.ManyToManyField(blank=True, help_text='Roles automatically granted with this role', related_name='implied_by', to='users.role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
