# Generated by Django 5.2.8 on 2026-04-26 18:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenant_created_at_alter_tenant_updated_at'),
        ('users', '0002_role_parent_role_permissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('password_complexity', models.CharField(default='high', max_length=20)),
                ('session_timeout', models.IntegerField(default=60)),
                ('mfa_required', models.BooleanField(default=True)),
                ('api_key_rotation', models.IntegerField(default=90)),
                ('ip_whitelist', models.TextField(blank=True, help_text='Comma-separated CIDR ranges')),
                ('failed_login_lock', models.IntegerField(default=5)),
                ('lock_duration', models.IntegerField(default=30)),
                ('concurrent_sessions', models.CharField(default='1', max_length=20)),
                ('tenant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_policy', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Security Policy',
                'verbose_name_plural': 'Security Policies',
            },
        ),
    ]
