# Generated by Django 5.2.8 on 2026-09-30 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_personalaccesstoken_delete_apikey"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name="SecurityPolicy",
                ),
            ]
        )
    ]
