# Generated by Django 5.2.8 on 2026-10-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_delete_securitypolicy"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_format",
            field=models.CharField(
                blank=True,
                help_text="Optional date format override",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(
                blank=True,
                help_text="User's personal language preference",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="theme_mode",
            field=models.CharField(
                choices=[("light", "Light"), ("dark", "Dark"), ("system", "System")],
                default="system",
                help_text="User's UI theme preference",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="timezone",
            field=models.CharField(
                blank=True,
                help_text="User's personal timezone preference",
                max_length=100,
                null=True,
            ),
        ),
    ]
