{'name': 'Recruiting',
    'odoo_equivalent': 'Recruitment',
    'technical_name': 'recruiting',
    'version': '1.0.0',
    'category': 'Human Resources',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'summary': 'Applicant tracking system (ATS).',
    'description': 'The Employees Recruitment module provides comprehensive functionality for managing hr recruitment within the '
                   'ERP system. It integrates seamlessly with other core applications.',
    'icon': 'UserPlus',
    'url': '/admin/recruiting',
    'depends': ['system', 'employees'],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],
    'display_name': 'Recruiting',
    'command_center_section': 'Human Resources',
    'sequence': 720,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Employees Recruitment Tile'}