{'name': 'Spreadsheet',
    'technical_name': 'spreadsheet',
    'version': '1.0.0',
    'category': 'Accounting',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'summary': 'Financial BI and reporting.',
    'description': 'Integrated spreadsheet editor.',
    'icon': 'Table',
    'url': '/admin/spreadsheet',
    'depends': ['core'],
    'installable': True,
    'application': True,
    'featured': False,
    'screenshots': [],
    'display_name': 'Spreadsheet',
    'command_center_section': 'Accounting & Finance',
    'sequence': 4,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Spreadsheet Tile'}