# Generated by Django 5.2.8 on 2026-09-16 17:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(help_text="e.g. 'Customer Support Agent'", max_length=100)),
                ('role', models.CharField(help_text="e.g. 'helpdesk', 'sales'", max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('system_prompt', models.TextField(help_text='The core instructions for the AI to follow.')),
                ('allowed_tools', models.JSONField(default=list, help_text="e.g. ['read_ticket', 'escalate']")),
            ],
            options={
                'verbose_name': 'AI Agent Profile',
                'verbose_name_plural': 'AI Agent Profiles',
                'db_table': 'ai_agent_profile',
            },
        ),
        migrations.CreateModel(
            name='AgentRunLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('triggered_by_model', models.CharField(blank=True, max_length=100)),
                ('triggered_by_id', models.CharField(blank=True, max_length=50)),
                ('user_input', models.TextField(blank=True, help_text='The original prompt that triggered the run.')),
                ('thoughts', models.TextField(blank=True, help_text='The step-by-step ReAct reasoning chain.')),
                ('actions_taken', models.JSONField(default=list, help_text='Tool calls made during the run.')),
                ('final_output', models.TextField(blank=True, help_text="The agent's final answer to the user.")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('escalated', 'Escalated')], default='success', max_length=20)),
                ('triggered_by', models.CharField(choices=[('user', 'User'), ('webhook', 'Webhook'), ('schedule', 'Schedule')], default='user', max_length=20)),
                ('tokens_used', models.IntegerField(default=0, help_text='Total tokens consumed in this run.')),
                ('duration_ms', models.IntegerField(default=0, help_text='Total execution time in milliseconds.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Agent Run Log',
                'db_table': 'ai_agent_run_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
