# Generated by Django 5.2.8 on 2026-09-23 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_rename_tables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentprofile',
            options={'verbose_name': 'Agent Profile', 'verbose_name_plural': 'Agent Profiles'},
        ),
    ]
