{'name': 'Discuss',
    'technical_name': 'discuss',
    'version': '1.0.0',
    'category': 'Discuss',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'summary': 'Internal messaging, group channels, and direct messaging.',
    'description': 'The Discuss module provides comprehensive functionality for managing discuss within the ERP system. '
                   'It integrates seamlessly with other core applications.',
    'icon': 'MessageSquare',
    'url': '/admin/discuss',
    'depends': ['system'],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],
    'display_name': 'Discuss',
    'command_center_section': 'Productivity',
    'sequence': 3,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Discuss Tile'}