{
    'name': 'Users',
    'technical_name': 'users',
    'version': '1.0.0',
    'category': 'Technical',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'category': 'Technical',
    'summary': 'User management, roles, permissions, and access control.',
    'description': 'The Identity & Access module provides comprehensive functionality for managing users within the ERP system. It integrates seamlessly with other core applications.',
    'icon': 'Users',
    'url': '/admin/users',
    'depends': ['system'],
    'installable': False,
    'application': False,
    'featured': True,
    'screenshots': [],

    'display_name': 'Users',
        'sequence': 99,
    'has_settings': False,
    'ui_paradigm': 'Hidden UI (Has React Components, but no Command Center Tile)',
    'navigation_path': 'Command Center -> Settings -> Users & Companies',
}
