{'name': 'Maintenance',
    'technical_name': 'maintenance',
    'version': '1.0.0',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'category': 'Maintenance',
    'summary': 'Equipment upkeep (preventative/corrective).',
    'description': 'The Maintenance module provides comprehensive functionality for managing maintenance within the ERP '
                   'system. It integrates seamlessly with other core applications.',
    'icon': 'Wrench',
    'url': '/admin/maintenance',
    'depends': ['system'],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],
    'display_name': 'Maintenance',
    'command_center_section': 'Manufacturing',
    'sequence': 4,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Maintenance Tile'}