# Generated by Django 5.2.8 on 2026-02-28 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=255)),
                ('resource', models.CharField(max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Metadata associated with the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
