# Generated by Django 5.2.8 on 2026-08-15 20:26

import apps.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='attachments/%Y/%m/', validators=[apps.core.validators.validate_document_file])),
                ('res_id', models.CharField(max_length=255)),
                ('mimetype', models.CharField(blank=True, max_length=100)),
                ('file_size', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('action', models.CharField(max_length=255)),
                ('resource_type', models.CharField(max_length=255)),
                ('resource_id', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomatedAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('model_name', models.CharField(help_text='e.g. crm.Lead, helpdesk.Ticket', max_length=100)),
                ('trigger', models.CharField(choices=[('on_create', 'On Record Creation'), ('on_write', 'On Record Update'), ('on_unlink', 'On Record Deletion'), ('on_stage_set', 'When Stage Is Set To'), ('on_time', 'Based on Time Condition')], max_length=30)),
                ('filter_domain', models.JSONField(blank=True, default=dict)),
                ('action_type', models.CharField(choices=[('update_field', 'Update a Field'), ('send_email', 'Send Email'), ('send_notification', 'Send In-App Notification'), ('create_activity', 'Schedule Activity'), ('call_webhook', 'Call External Webhook')], max_length=30)),
                ('action_data', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Automated Action',
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('fiscal_year_end_month', models.IntegerField(default=12)),
                ('enable_multicurrency', models.BooleanField(default=False)),
                ('setup_completed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FieldChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('object_id', models.CharField(max_length=255, verbose_name='Record ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='Field')),
                ('field_label', models.CharField(blank=True, max_length=100, verbose_name='Field Label')),
                ('old_value', models.TextField(blank=True, verbose_name='Previous Value')),
                ('new_value', models.TextField(blank=True, verbose_name='New Value')),
            ],
            options={
                'verbose_name': 'Field Change Log',
                'verbose_name_plural': 'Field Change Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('partner_type', models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('both', 'Customer & Supplier'), ('internal', 'Internal')], default='customer', max_length=20)),
                ('payment_terms', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bio', models.TextField(blank=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='partners/%Y/%m/%d/', validators=[apps.core.validators.validate_image_file])),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(default='en-us', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecordActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('object_id', models.CharField(max_length=255, verbose_name='Record ID')),
                ('activity_type', models.CharField(choices=[('call', 'Phone Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('todo', 'To-Do'), ('upload', 'Upload Document'), ('custom', 'Custom')], default='todo', max_length=30, verbose_name='Activity Type')),
                ('summary', models.CharField(blank=True, help_text='Short description shown on the kanban card.', max_length=255, verbose_name='Summary')),
                ('note', models.TextField(blank=True, verbose_name='Notes')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('is_done', models.BooleanField(default=False, verbose_name='Done')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('feedback', models.TextField(blank=True, verbose_name='Completion Note')),
            ],
            options={
                'verbose_name': 'Record Activity',
                'verbose_name_plural': 'Record Activities',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='RecordFollower',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('object_id', models.CharField(max_length=255, verbose_name='Record ID')),
                ('notify_on_message', models.BooleanField(default=True)),
                ('notify_on_activity', models.BooleanField(default=True)),
                ('notify_on_stage_change', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Record Follower',
                'verbose_name_plural': 'Record Followers',
            },
        ),
        migrations.CreateModel(
            name='RecordMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('object_id', models.CharField(max_length=255, verbose_name='Record ID')),
                ('message_type', models.CharField(choices=[('comment', 'Message'), ('note', 'Internal Note'), ('email', 'Inbound Email'), ('notification', 'Notification')], default='note', max_length=20, verbose_name='Message Type')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Subject')),
                ('body', models.TextField(blank=True, verbose_name='Body')),
                ('is_internal', models.BooleanField(default=False, help_text='Internal notes are only visible to team members, not sent externally.', verbose_name='Internal Note')),
                ('attachment_ids', models.JSONField(blank=True, default=list, help_text='List of Attachment UUIDs linked to this message.')),
            ],
            options={
                'verbose_name': 'Record Message',
                'verbose_name_plural': 'Record Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=100)),
                ('method_name', models.CharField(max_length=100)),
                ('interval_number', models.IntegerField(default=1)),
                ('interval_type', models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], default='days', max_length=20)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Scheduled Action',
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('prefix', models.CharField(max_length=20)),
                ('padding', models.IntegerField(default=5)),
                ('next_number', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UoM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('factor', models.FloatField(default=1.0, help_text='Ratio to reference UoM in this category')),
                ('is_reference', models.BooleanField(default=False, help_text='Is this the base unit for this category?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UoMCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
