# Generated by Django 5.2.8 on 2026-10-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_fieldhistory_delete_fieldchangelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="installedmodule",
            name="has_settings",
            field=models.BooleanField(
                default=False, help_text="Does this module have a settings menu?"
            ),
        ),
        migrations.AddField(
            model_name="installedmodule",
            name="settings_url",
            field=models.CharField(
                blank=True, help_text="e.g. /admin/crm/settings", max_length=255
            ),
        ),
    ]
