{'name': 'Core',
    'technical_name': 'core',
    'version': '1.0.0',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'category': 'Technical',
    'summary': 'Abstract base models and global routing.',
    'description': 'The Core module provides comprehensive functionality for managing core within the ERP system. It '
                   'integrates seamlessly with other core applications.',
    'icon': 'Layers',
    'url': '/admin/core',
    'depends': ['system'],
    'installable': True,
    'application': False,
    'featured': True,
    'screenshots': [],
    'display_name': 'Core',
    'sequence': 999,
    'has_settings': False,
    'ui_paradigm': 'Headless Core (Pure Python Backend, No React UI)',
    'navigation_path': 'Background Service (No UI. Foundational Models)'}