{'name': 'Shop Floor',
    'technical_name': 'shop_floor',
    'version': '1.0.0',
    'category': 'Manufacturing',
    'author': 'BitGuard',
    'summary': 'Shop Floor module',
    'description': 'Core functionality for Shop Floor',
    'icon': 'Box',
    'url': '/admin/shop_floor',
    'depends': ['system'],
    'installable': True,
    'application': True,
    'command_center_section': 'Manufacturing',
    'sequence': 2}