{'name': 'Calendar',
    'technical_name': 'calendar',
    'version': '1.0.0',
    'category': 'Productivity',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'summary': 'Internal meeting scheduling.',
    'description': 'Schedule meetings and events.',
    'icon': 'Calendar',
    'url': '/admin/calendar',
    'depends': ['core'],
    'installable': True,
    'application': True,
    'featured': False,
    'screenshots': [],
    'display_name': 'Calendar',
    'command_center_section': 'Productivity',
    'sequence': 7,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Calendar Tile'}