{'name': 'Barcode',
    'technical_name': 'barcode',
    'version': '1.0.0',
    'summary': 'Mobile scanner operations.',
    'description': 'Barcode for BitGuard ERP',
    'category': 'Inventory',
    'author': 'BitGuard',
    'website': 'https://www.bitguard.com',
    'depends': ['core', 'system'],
    'installable': True,
    'application': True,
    'auto_install': False,
    'icon': 'Smartphone',
    'url': '/admin/barcode',
    'screenshots': [],
    'display_name': 'Barcode',
    'command_center_section': 'Inventory',
    'sequence': 3,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Barcode Tile'}