# Generated by Django 5.2.8 on 2026-07-17 11:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_setup', '0003_incomingmailserver_outgoingmailserver_erpmodule_and_more'),
        ('tenants', '0003_tenant_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=500)),
                ('body_html', models.TextField(blank=True)),
                ('body_text', models.TextField(blank=True)),
                ('model', models.CharField(blank=True, help_text='e.g. sale.order — applies to this model', max_length=100)),
                ('reply_to', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('lang', models.CharField(blank=True, help_text='e.g. en_US', max_length=10)),
                ('use_default_to', models.BooleanField(default=True)),
                ('partner_to', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Email Template',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='audittrail',
            name='action',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['action', 'tenant'], name='base_setup__action_e44b05_idx'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant'),
        ),
    ]
