{'name': 'Sales',
    'technical_name': 'sale',
    'version': '1.0.0',
    'category': 'Sales',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'summary': 'Core quoting and sales orders.',
    'description': 'The Sale module provides comprehensive functionality for managing sale within the ERP system. It '
                   'integrates seamlessly with other core applications.',
    'icon': 'ShoppingBag',
    'url': '/admin/sales',
    'depends': ['system'],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],
    'display_name': 'Sales',
    'command_center_section': 'Sales',
    'sequence': 1,
    'has_settings': True,
    'settings_url': '/admin/settings/sale',
    'settings_desc': 'Configure settings',
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Sale Tile'}