# Generated by Django 5.0.14 on 2026-06-19 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0001_initial'),
        ('services', '0001_initial'),
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='linked_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_pages', to='services.serviceitem'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='og_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms.mediaasset'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant'),
        ),
    ]
