{
    'name': 'Marketing Automation',
    'technical_name': 'marketing',
    'version': '1.0.0',
    'category': 'Marketing',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'category': 'Marketing',
    'summary': 'Email campaigns, automation, analytics, and contact management.',
    'description': 'The Marketing module provides comprehensive functionality for managing marketing within the ERP system. It integrates seamlessly with other core applications.',
    'icon': 'Megaphone',
    'url': '/admin/marketing',
    'depends': ['system', 'crm'],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],

    'display_name': 'Marketing',
    'command_center_section': 'Marketing',
    'sequence': 1,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Marketing Tile',
}
