{'name': 'Expenses',
    'technical_name': 'hr_expense',
    'version': '1.0.0',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'category': 'Human Resources',
    'summary': 'Employee reimbursements.',
    'description': 'The Hr Expense module provides comprehensive functionality for managing hr expense within the ERP '
                   'system. It integrates seamlessly with other core applications.',
    'icon': 'Receipt',
    'url': '/admin/expenses',
    'depends': ['system', 'hr', 'accounting'],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],
    'display_name': 'Expenses',
    'command_center_section': 'Human Resources',
    'sequence': 7,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Hr Expense Tile'}