{'name': 'Appraisals',
    'technical_name': 'hr_appraisal',
    'version': '1.0.0',
    'category': 'Human Resources',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'summary': 'Periodic performance reviews.',
    'description': 'The Hr Appraisal module provides comprehensive functionality for managing hr appraisal within the ERP '
                   'system. It integrates seamlessly with other core applications.',
    'icon': 'ClipboardCheck',
    'url': '/admin/appraisals',
    'depends': ['system', 'hr'],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],
    'display_name': 'Appraisals',
    'command_center_section': 'Human Resources',
    'sequence': 8,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Hr Appraisal Tile'}