{'name': 'IoT',
    'technical_name': 'iot',
    'version': '1.0.0',
    'summary': 'Machine integration (scales, cameras, foot pedals).',
    'description': 'IoT for BitGuard ERP',
    'category': 'IoT',
    'author': 'BitGuard',
    'website': 'https://www.bitguard.com',
    'depends': ['core', 'system'],
    'installable': True,
    'application': True,
    'auto_install': False,
    'icon': 'Cpu',
    'url': '/admin/iot',
    'screenshots': [],
    'display_name': 'IoT',
    'command_center_section': 'Manufacturing',
    'sequence': 7,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Iot Tile'}