{
    'name': 'AI Agent',
    'technical_name': 'ai_agent',
    'version': '1.0',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'category': 'Administration',
    'display_name': 'AI Agent',
    'summary': 'AI-powered virtual employees for automation and intelligent workflows.',
    'description': 'Provides Virtual Employees powered by LLMs to automate tasks across the ERP.',
    'icon': 'Bot',
    'url': '/admin/ai_agent',
    'depends': ['ai_engine', 'system'],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],
    'command_center_section': 'Administration',
    'sequence': 98,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center → AI Agent Tile → /admin/ai_agent',
}
