{'name': 'Point of Sale',
    'technical_name': 'pos',
    'version': '1.0.0',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'category': 'Point of Sale',
    'summary': 'Retail and restaurant registers.',
    'description': 'The Pos module provides comprehensive functionality for managing pos within the ERP system. It '
                   'integrates seamlessly with other core applications.',
    'icon': 'ShoppingCart',
    'url': '/admin/pos',
    'depends': ['system'],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],
    'display_name': 'Point of Sale',
    'command_center_section': 'Sales',
    'sequence': 3,
    'has_settings': True,
    'settings_url': '/admin/settings/pos',
    'settings_desc': 'Configure settings',
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Pos Tile'}