{'name': 'Rental',
    'technical_name': 'rental',
    'version': '1.0.0',
    'category': 'Rental',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'summary': 'Time-based equipment/service rentals.',
    'description': 'The Rental module provides comprehensive functionality for managing rental within the ERP system. It '
                   'integrates seamlessly with other core applications.',
    'icon': 'Key',
    'url': '/admin/rental',
    'depends': ['system'],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],
    'display_name': 'Rental',
    'command_center_section': 'Sales',
    'sequence': 5,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Rental Tile'}