{'name': 'Journeys',
    'technical_name': 'journeys',
    'version': '1.0.0',
    'category': 'Email Marketing',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'summary': 'Email campaigns, automation, analytics, and contact management.',
    'description': 'The Journeys module provides comprehensive functionality for managing marketing within the ERP '
                   'system. It integrates seamlessly with other core applications.',
    'icon': 'Megaphone',
    'url': '/admin/journeys',
    'depends': ['system', 'crm'],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],
    'display_name': 'Journeys',
    'command_center_section': 'Marketing',
    'sequence': 650,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Journeys Tile'}