{'name': 'Live Chat',
    'technical_name': 'livechat',
    'display_name': 'Live Chat',
    'version': '1.0.0',
    'category': 'Discuss',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'summary': 'Website visitor chatting.',
    'description': 'Engage with website visitors in real-time.',
    'icon': 'MessageSquare',
    'url': '/admin/livechat',
    'depends': ['core'],
    'installable': True,
    'application': True,
    'featured': False,
    'screenshots': [],
    'module_type': 'integration',
    'command_center_section': 'Website',
    'sequence': 6,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Livechat Tile'}