{
    'name': 'Apps',
    'technical_name': 'apps',
    'version': '1.0.0',
    'category': 'Administration',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'summary': 'App Store and Module Installer',
    'description': 'The Apps module allows you to install, upgrade, and uninstall modules in your ERP system.',
    'icon': 'Grid',
    'url': '/admin/apps',
    'depends': ['system'],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],
    'display_name': 'Apps',
    'command_center_section': 'Administration',
    'sequence': 2,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Apps Tile',
}
