# Generated by Django 5.2.8 on 2026-05-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_billingsettings_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='seat_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of user seats in this subscription'),
        ),
    ]
