{'name': 'Tasks',
    'odoo_equivalent': 'Note/To-Do',
    'technical_name': 'tasks',
    'version': '1.0.0',
    'category': 'Productivity',
    'author': 'BitGuard',
    'display_name': 'Tasks',
    'summary': 'To-Do module',
    'description': 'Core functionality for To-Do',
    'icon': 'Box',
    'url': '/admin/tasks',
    'depends': ['system'],
    'installable': True,
    'application': True,
    'command_center_section': 'Productivity',
    'sequence': 910}