{'name': 'Campaigns',
    'odoo_equivalent': 'Email Marketing',
    'technical_name': 'campaigns',
    'display_name': 'Campaigns',
    'version': '1.0.0',
    'category': 'Email Marketing',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'summary': 'Newsletters and blast emails.',
    'description': 'Design and send mass email campaigns.',
    'icon': 'Mail',
    'url': '/admin/campaigns',
    'depends': ['core'],
    'installable': True,
    'application': True,
    'featured': False,
    'screenshots': [],
    'module_type': 'integration',
    'command_center_section': 'Marketing',
    'sequence': 610,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Mass Mailing Tile',
    'has_settings': True,
    'settings_url': '/admin/settings/campaigns'
}