from rest_framework.permissions import IsAuthenticated
from apps.core.utils.response import standard_response
from apps.core.api.permissions import IsPlatformAdmin
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import filters
from apps.core.domain.models import InstalledModule, CommandCenterSection
from apps.core.api.serializers import InstalledModuleSerializer, CommandCenterSectionSerializer
from rest_framework import viewsets, permissions, status
from rest_framework.response import Response
from rest_framework.decorators import action
from apps.core.services.command_center import CommandCenterAnalyticsService

class AnalyticsViewSet(viewsets.ViewSet):
    permission_classes = [permissions.IsAuthenticated]

    @action(detail=False, methods=['get'])
    def global_metrics(self, request):
        tenant = getattr(request.user, 'tenant', None)
        date_range = request.query_params.get('range', '30days')
        
        # Call the Orchestrator Service (Tier-1 Standard)
        metrics = CommandCenterAnalyticsService.get_global_metrics(tenant=tenant, date_range=date_range)
        
        return Response(metrics)

    @action(detail=False, methods=['get'])
    def system_health(self, request):
        tenant = getattr(request.user, 'tenant', None)
        date_range = request.query_params.get('range', '30days')
        metrics = CommandCenterAnalyticsService.get_global_metrics(tenant=tenant, date_range=date_range)
        return Response(metrics.get("system_health", {}))

from ..domain.models import Sequence
from .serializers import SequenceSerializer
from apps.core.api.mixins import TenantScopedMixin

class SequenceViewSet(TenantScopedMixin, viewsets.ModelViewSet):
    queryset = Sequence.objects.all()
    serializer_class = SequenceSerializer
    permission_classes = [permissions.IsAuthenticated]


from apps.core.domain.models import Language, Translation
from apps.core.api.serializers import LanguageSerializer, TranslationSerializer
from rest_framework.decorators import action
from rest_framework.response import Response

class LanguageViewSet(TenantScopedMixin, viewsets.ModelViewSet):
    queryset = Language.objects.all()
    serializer_class = LanguageSerializer
    permission_classes = [permissions.IsAuthenticated]
    
    def get_queryset(self):
        user = self.request.user
        qs = super().get_queryset()
        if not user.is_superuser and getattr(user, 'tenant', None):
            qs = qs.filter(tenant=user.tenant)
        return qs

class TranslationViewSet(TenantScopedMixin, viewsets.ModelViewSet):
    queryset = Translation.objects.all()
    serializer_class = TranslationSerializer
    permission_classes = [permissions.IsAuthenticated]
    
    def get_permissions(self):
        if self.action == 'locales':
            return []
        return super().get_permissions()

    @action(detail=False, methods=['get'], permission_classes=[])
    def locales(self, request):
        lng = request.query_params.get('lng', 'en')
        # Return translations mapped name: value
        translations = Translation.objects.filter(language__code=lng)
        
        # In a real multi-tenant scenario we might also filter by tenant,
        # but for public login screen, we might need a generic or domain-based tenant lookup.
        # For now, just return all matching or base ones.
        
        data = {t.name: t.value for t in translations}
        return Response(data)

    @action(detail=False, methods=['get'])
    def export(self, request):
        from django.http import HttpResponse
        language = request.query_params.get('language', 'en')
        fmt = request.query_params.get('format', 'po')
        tenant = getattr(request.user, 'tenant', None)
        
        lines = []
        lines.append(f'# Translation file for language: {language}')
        lines.append(f'# Generated by BitGuard ERP')
        lines.append(f'# Format: {fmt}')
        lines.append('')
        
        try:
            translations = Translation.objects.filter(tenant=tenant, language__code=language)
            for t in translations:
                lines.append(f'msgid "{t.name}"')
                lines.append(f'msgstr "{t.value}"')
                lines.append('')
        except Exception:
            pass
        
        content = '\n'.join(lines)
        content_type = 'text/x-po' if fmt == 'po' else 'text/csv'
        ext = fmt if fmt in ['po', 'csv'] else 'po'
        response = HttpResponse(content, content_type=f'{content_type}; charset=utf-8')
        response['Content-Disposition'] = f'attachment; filename="translations_{language}.{ext}"'
        return response

class CommandCenterSectionViewSet(TenantScopedMixin, viewsets.ModelViewSet):
    queryset = CommandCenterSection.objects.all()
    serializer_class = CommandCenterSectionSerializer
    permission_classes = [permissions.IsAuthenticated]
    pagination_class = None # Return a simple flat list

class InstalledModuleViewSet(TenantScopedMixin, viewsets.ModelViewSet):
    """
    API endpoint that allows ERP modules to be viewed, installed, or uninstalled.
    """
    queryset = InstalledModule.objects.all()
    serializer_class = InstalledModuleSerializer
    permission_classes = [permissions.IsAuthenticated]
    pagination_class = None
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    search_fields = ['name', 'technical_name', 'summary', 'category']
    filterset_fields = ['is_installed', 'category']

    @action(detail=False, methods=['get'])
    def categories(self, request):
        qs = self.filter_queryset(self.get_queryset())
        from django.db.models import Count
        categories = qs.values('category').annotate(count=Count('id')).order_by('category')
        result = [
            {'name': c['category'] or 'Uncategorized', 'count': c['count']}
            for c in categories
        ]
        return Response(result)
    ordering_fields = ['name', 'category']
    ordering = ['category', 'name']

    def get_queryset(self):
        tenant = getattr(self.request, 'tenant', None)
        qs = super().get_queryset()
        
        # By default, only show user-facing applications (unless explicitly queried)
        if self.request.query_params.get('all') != 'true':
            qs = qs.filter(application=True)
            
        if tenant:
            return qs.filter(tenant=tenant)
        return qs

    @action(detail=False, methods=['post'])
    def update_list(self, request):
        tenant = getattr(request, 'tenant', None)
        from apps.core.services.modules import sync_modules
        count = sync_modules(tenant)
        return Response({'status': 'success', 'modules_found': count})

    @action(detail=True, methods=['post'], permission_classes=[IsPlatformAdmin])
    def install(self, request, pk=None):
        module = self.get_object()
        
        from apps.core.services.modules import install_module
        tenant = getattr(request, 'tenant', None)
        
        success, unmet_deps = install_module(module, tenant=tenant)
        
        if not success:
            return Response({
                'error': 'Dependencies not installed',
                'unmet_dependencies': unmet_deps
            }, status=status.HTTP_400_BAD_REQUEST)
            
        return Response({'status': 'installed', 'module': module.technical_name})

    @action(detail=True, methods=['post'], permission_classes=[IsPlatformAdmin])
    def upgrade(self, request, pk=None):
        module = self.get_object()
        if not module.is_installed:
            return Response({'error': 'Module is not installed'}, status=status.HTTP_400_BAD_REQUEST)
        
        from apps.core.services.modules import find_manifest, read_manifest
        manifest_path = find_manifest(module.technical_name)
        if manifest_path:
            data = read_manifest(manifest_path)
            module.version = data.get('version', module.version)
            module.summary = data.get('summary', module.summary)
            module.description = data.get('description', module.description)
            module.save()
        else:
            return Response({'error': 'Manifest not found'}, status=404)
            
        tenant = getattr(request, 'tenant', None)
        try:
            from apps.core.domain.models import AuditTrail
            AuditTrail.objects.create(
                action='update',
                resource_type='InstalledModule',
                resource_id=str(module.id),
                details={'technical_name': module.technical_name, 'message': 'Module upgraded'},
                tenant=tenant
            )
        except Exception:
            pass
            
        return Response({'status': 'upgraded', 'module': module.technical_name})

    @action(detail=True, methods=['post'], permission_classes=[IsPlatformAdmin])
    def uninstall(self, request, pk=None):
        module = self.get_object()
        
        # --- KERNEL PROTECTION ---
        KERNEL_MODULES = ['core', 'system', 'auth', 'tenants', 'automation', 'apps', 'users']
        if module.technical_name in KERNEL_MODULES:
            return Response({
                'error': f"Cannot uninstall '{module.technical_name}'. It is a protected core kernel module required for the ERP to function.",
                'blocking_modules': ['ERP Core Engine']
            }, status=status.HTTP_403_FORBIDDEN)
        # -------------------------
        
        # Check no installed module depends on this one
        dependents = InstalledModule.objects.filter(
            tenant=module.tenant,
            is_installed=True
        ).exclude(id=module.id)
        
        blocking = [m.technical_name for m in dependents if isinstance(m.depends, list) and module.technical_name in m.depends]
        
        if blocking:
            return Response({
                'error': 'Other installed modules depend on this module',
                'blocking_modules': blocking
            }, status=status.HTTP_400_BAD_REQUEST)
        
        module.is_installed = False
        module.save()
        
        tenant = getattr(request, 'tenant', None)
        try:
            from apps.core.domain.models import AuditTrail
            AuditTrail.objects.create(
                action='uninstall_module',
                resource_type='InstalledModule',
                resource_id=str(module.id),
                details={'technical_name': module.technical_name},
                tenant=tenant
            )
        except Exception:
            pass
            
        return Response({'status': 'uninstalled', 'module': module.technical_name})




from django_filters.rest_framework import DjangoFilterBackend
from django.http import HttpResponse
from apps.core.api.serializers import AuditTrailSerializer

class AuditTrailViewSet(TenantScopedMixin, viewsets.ReadOnlyModelViewSet):
    """
    API endpoint that allows audit logs to be viewed.
    Using central AuditTrail model for system-wide transparency.
    """
    from apps.core.domain.models import AuditTrail
    queryset = AuditTrail.objects.all()
    serializer_class = AuditTrailSerializer
    permission_classes = [permissions.IsAuthenticated, IsPlatformAdmin]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    search_fields = ['action', 'resource_type', 'user__email', 'details']
    filterset_fields = ['action', 'resource_type']
    ordering_fields = ['created_at']
    
    def get_queryset(self):
        user = self.request.user
        if user.is_superuser:
            return self.queryset
        if getattr(user, 'tenant', None):
            return self.queryset.filter(tenant=user.tenant)
        return self.queryset

    @action(detail=False, methods=['get'])
    def export_csv(self, request):
        import csv
        queryset = self.filter_queryset(self.get_queryset())
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="audit_logs_export.csv"'
        writer = csv.writer(response)
        writer.writerow(['Date', 'User', 'Action', 'Resource', 'Details'])
        for log in queryset:
            writer.writerow([log.created_at, log.user.email if log.user else 'System', log.action, log.resource_type, log.details])
        return response

from apps.core.api.serializers import SystemParameterSerializer
from apps.core.domain.models import SystemParameter
from apps.core.services.system_parameters import SystemParametersService

class SystemParameterViewSet(TenantScopedMixin, viewsets.ModelViewSet):
    """
    ViewSet for managing System Parameters.
    """
    serializer_class = SystemParameterSerializer
    permission_classes = [permissions.IsAuthenticated]
    
    def get_queryset(self):
        return SystemParameter.objects.filter(tenant=self.request.user.tenant)
        
    def perform_create(self, serializer):
        serializer.save(tenant=self.request.user.tenant)
        
    def perform_destroy(self, instance):
        SystemParametersService.delete_param(instance)

from apps.core.api.serializers import ScheduledActionSerializer
from apps.core.domain.models import ScheduledAction
class ScheduledActionViewSet(TenantScopedMixin, viewsets.ModelViewSet):
    queryset = ScheduledAction.objects.all()
    serializer_class = ScheduledActionSerializer
    permission_classes = [permissions.IsAuthenticated, IsPlatformAdmin]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter]
    search_fields = ['name', 'model_name', 'method_name']
    pagination_class = None

    def perform_create(self, serializer):
        tenant = getattr(self.request, 'tenant', None) or getattr(self.request.user, 'tenant', None)
        serializer.save(tenant=tenant)

    @action(detail=True, methods=['post'])
    def run(self, request, pk=None):
        action = self.get_object()
        from django.apps import apps
        from django.utils import timezone
        import traceback
        
        try:
            # Resolve model
            app_label, model_name = action.model_name.split('.')
            model_class = apps.get_model(app_label, model_name)
            
            # Execute method
            method = getattr(model_class.objects, action.method_name, None)
            if not method:
                method = getattr(model_class, action.method_name, None)
            
            if not method:
                raise AttributeError(f"Method '{action.method_name}' not found on model '{action.model_name}'")
            
            # Call method
            method()
            
            action.last_run = timezone.now()
            action.last_error = ''
            
            # Calculate next run
            from dateutil.relativedelta import relativedelta
            if action.interval_type == 'minutes':
                delta = relativedelta(minutes=action.interval_number)
            elif action.interval_type == 'hours':
                delta = relativedelta(hours=action.interval_number)
            elif action.interval_type == 'days':
                delta = relativedelta(days=action.interval_number)
            elif action.interval_type == 'weeks':
                delta = relativedelta(weeks=action.interval_number)
            elif action.interval_type == 'months':
                delta = relativedelta(months=action.interval_number)
            else:
                delta = relativedelta(days=action.interval_number)
            
            action.next_run = timezone.now() + delta
            action.save()
            return Response({"status": "success", "message": f"Action '{action.name}' executed successfully."})
        except Exception as e:
            error_msg = f"Error executing {action.name}: {str(e)}\n{traceback.format_exc()}"
            action.last_run = timezone.now()
            action.last_error = error_msg
            action.save()
            return Response({"status": "error", "message": str(e), "details": error_msg}, status=400)








from apps.core.api.serializers import ContentTypeSerializer
from django.contrib.contenttypes.models import ContentType
class ContentTypeViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = ContentType.objects.all()
    serializer_class = ContentTypeSerializer
    permission_classes = [permissions.IsAuthenticated]
    pagination_class = None

    def list(self, request, *args, **kwargs):
        queryset = self.filter_queryset(self.get_queryset())
        serializer = self.get_serializer(queryset, many=True)
        # Grouping by app_label to match expected format
        from collections import defaultdict
        grouped = defaultdict(list)
        for item in serializer.data:
            grouped[item['app_label']].append(item)
        return standard_response(True, "Content Types", dict(grouped))



from ..domain.models import DatabaseBackup
from .serializers import DatabaseBackupSerializer

class DatabaseBackupViewSet(TenantScopedMixin, viewsets.ReadOnlyModelViewSet):
    queryset = DatabaseBackup.objects.all()
    serializer_class = DatabaseBackupSerializer

from ..domain.models import UoMCategory, UoM
from .serializers import UoMCategorySerializer, UoMSerializer

class UoMCategoryViewSet(TenantScopedMixin, viewsets.ModelViewSet):
    """
    ViewSet for Unit of Measurement Categories
    """
    queryset = UoMCategory.objects.all()
    serializer_class = UoMCategorySerializer
    search_fields = ['name']
    ordering_fields = ['name']
    ordering = ['name']

class UoMViewSet(TenantScopedMixin, viewsets.ModelViewSet):
    """
    ViewSet for Units of Measurement
    """
    queryset = UoM.objects.select_related('category').all()
    serializer_class = UoMSerializer
    filterset_fields = ['category', 'is_reference']
    search_fields = ['name', 'category__name']
    ordering_fields = ['name', 'factor']
    ordering = ['category', 'name']



from ..domain.models import Country, State
from .serializers import CountrySerializer, StateSerializer
from rest_framework.views import APIView
from rest_framework.response import Response

class CountryViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Country.all_objects.filter(is_deleted=False)
    serializer_class = CountrySerializer
    permission_classes = [permissions.IsAuthenticated]
    pagination_class = None

class StateViewSet(viewsets.ReadOnlyModelViewSet):
    serializer_class = StateSerializer
    permission_classes = [permissions.IsAuthenticated]
    pagination_class = None
    
    def get_queryset(self):
        qs = State.all_objects.filter(is_deleted=False)
        country_id = self.request.query_params.get('country')
        if country_id:
            qs = qs.filter(country_id=country_id)
        return qs

class ConfigOptionsView(APIView):
    permission_classes = [permissions.IsAuthenticated]

    def get(self, request):
        try:
            import zoneinfo
            timezones = sorted(list(zoneinfo.available_timezones()))
        except ImportError:
            timezones = ['UTC', 'America/New_York', 'Europe/Paris']
        
        data = {
            'timezones': timezones,
            'paper_formats': [
                {'id': 'A4', 'name': 'A4 (210 x 297 mm)'},
                {'id': 'Letter', 'name': 'US Letter (8.5 x 11 inches)'},
                {'id': 'Legal', 'name': 'US Legal (8.5 x 14 inches)'},
            ]
        }
        return Response(data)

from .serializers import CompanySerializer
from ..domain.models import Company

class CompanyViewSet(TenantScopedMixin, viewsets.ModelViewSet):
    serializer_class = CompanySerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        tenant = getattr(self.request, 'tenant', None)
        return Company.objects.filter(tenant=tenant)
        
    @action(detail=False, methods=['get', 'patch'])
    def my_company(self, request):
        # Odoo concept: Get the user's primary company for their tenant
        # Since Tenant equates to a single main company right now, get the first one.
        tenant = getattr(request, 'tenant', None)
        
        if not tenant:
            return Response({'detail': 'No active tenant found.'}, status=400)
            
        company = Company.objects.filter(tenant=tenant).first()
        
        if not company:
            # Auto-create the main company for the tenant if it doesn't exist yet
            company = Company.objects.create(
                tenant=tenant, 
                name=tenant.name,
                email=tenant.email if hasattr(tenant, 'email') else ''
            )
            
        if request.method == 'PATCH':
            serializer = self.get_serializer(company, data=request.data, partial=True)
            serializer.is_valid(raise_exception=True)
            serializer.save()
            return Response(serializer.data)
            
        serializer = self.get_serializer(company)
        return Response(serializer.data)


class CurrencyViewSet(TenantScopedMixin, viewsets.ModelViewSet):
    permission_classes = [IsAuthenticated]
    from apps.core.api.serializers import CurrencySerializer
    serializer_class = CurrencySerializer
    pagination_class = None
    def get_queryset(self): 
        from apps.core.domain.models import Currency
        tenant = getattr(self.request, 'tenant', None)
        return Currency.all_objects.filter(Q(tenant=tenant) | Q(tenant__isnull=True), is_deleted=False)

