{'name': 'Dashboards',
    'technical_name': 'board',
    'version': '1.0.0',
    'category': 'Productivity',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'summary': 'Custom KPI dashboards and pinned executive views.',
    'description': 'The Enterprise Dashboards module provides comprehensive functionality for managing board within the '
                   'ERP system. It integrates seamlessly with other core applications.',
    'icon': 'LayoutDashboard',
    'url': '/admin/board/analytics',
    'depends': ['system'],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],
    'display_name': 'Dashboards',
    'command_center_section': 'Accounting & Finance',
    'sequence': 5,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Board Tile'}