# Generated by Django 5.2.8 on 2026-08-15 20:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QualityAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('product_id', models.IntegerField(help_text='Reference to inventory product')),
                ('team_id', models.IntegerField(help_text='Reference to Quality Team')),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('0', 'Normal'), ('1', 'Low'), ('2', 'High'), ('3', 'Very High')], default='0', max_length=10)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('action', 'Action Proposed'), ('close', 'Closed')], default='draft', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('lot_name', models.CharField(blank=True, max_length=50)),
                ('result', models.CharField(choices=[('none', 'To Do'), ('pass', 'Pass'), ('fail', 'Fail')], default='none', max_length=20)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='QualityPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('operation', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing'), ('manufacturing', 'Manufacturing')], default='incoming', max_length=50)),
                ('team', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
