# Generated by Django 5.2.8 on 2026-08-15 20:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('product_id', models.IntegerField(blank=True, default=0, help_text='Reference to inventory product', null=True)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('quantity', models.FloatField(default=1.0)),
                ('type', models.CharField(choices=[('normal', 'Manufacture this product'), ('phantom', 'Kit')], default='normal', max_length=20)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillOfMaterialLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('component_id', models.IntegerField(blank=True, default=0, help_text='FK to inventory.InventoryItem', null=True)),
                ('component_name', models.CharField(blank=True, max_length=255)),
                ('quantity', models.FloatField(default=1.0)),
                ('sequence', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturingOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('product_id', models.IntegerField(blank=True, default=0, help_text='Reference to inventory product', null=True)),
                ('qty_producing', models.FloatField(default=0.0)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancel', 'Cancelled')], default='draft', max_length=20)),
                ('date_planned_start', models.DateTimeField(blank=True, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('qty_to_produce', models.FloatField(default=1.0)),
                ('date_planned_finished', models.DateTimeField(blank=True, null=True)),
                ('origin', models.CharField(blank=True, help_text='Source document (SO number)', max_length=100)),
                ('lot_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Routing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoutingOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('sequence', models.IntegerField(default=10)),
                ('duration_expected', models.FloatField(default=60, help_text='Minutes')),
            ],
        ),
        migrations.CreateModel(
            name='ScrapOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('inventory_item_id', models.IntegerField(blank=True, default=0, null=True)),
                ('component_name', models.CharField(blank=True, max_length=255)),
                ('quantity', models.FloatField(default=1.0)),
                ('reason', models.TextField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('capacity', models.FloatField(default=1.0)),
                ('time_efficiency', models.FloatField(default=100.0)),
                ('color', models.CharField(default='#3b82f6', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('costs_hour', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancel', 'Cancelled')], default='pending', max_length=20)),
                ('duration_expected', models.FloatField(default=60)),
                ('duration_real', models.FloatField(default=0)),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('date_finished', models.DateTimeField(blank=True, null=True)),
                ('sequence', models.IntegerField(default=10)),
            ],
        ),
    ]
