# Generated by Django 5.2.8 on 2026-07-16 20:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0001_initial'),
        ('tenants', '0003_tenant_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billofmaterial',
            name='product',
        ),
        migrations.RemoveField(
            model_name='billofmaterial',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='manufacturingorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='manufacturingorder',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='manufacturingorder',
            name='status',
        ),
        migrations.RemoveField(
            model_name='workcenter',
            name='cost_per_hour',
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='product_id',
            field=models.IntegerField(blank=True, default=0, help_text='Reference to inventory product', null=True),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='product_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='type',
            field=models.CharField(choices=[('normal', 'Manufacture this product'), ('phantom', 'Kit')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='lot_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='origin',
            field=models.CharField(blank=True, help_text='Source document (SO number)', max_length=100),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='product_id',
            field=models.IntegerField(blank=True, default=0, help_text='Reference to inventory product', null=True),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='product_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='qty_producing',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='qty_to_produce',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancel', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='workcenter',
            name='color',
            field=models.CharField(default='#3b82f6', max_length=7),
        ),
        migrations.AddField(
            model_name='workcenter',
            name='costs_hour',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billofmaterial',
            name='quantity',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='date_planned_finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='date_planned_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='workcenter',
            name='capacity',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='workcenter',
            name='time_efficiency',
            field=models.FloatField(default=100.0),
        ),
        migrations.CreateModel(
            name='BillOfMaterialLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('component_id', models.IntegerField(blank=True, default=0, help_text='FK to inventory.InventoryItem', null=True)),
                ('component_name', models.CharField(blank=True, max_length=255)),
                ('quantity', models.FloatField(default=1.0)),
                ('sequence', models.IntegerField(default=10)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='mrp.billofmaterial')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Routing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='routing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mrp.routing'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='routing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mrp.routing'),
        ),
        migrations.CreateModel(
            name='RoutingOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('sequence', models.IntegerField(default=10)),
                ('duration_expected', models.FloatField(default=60, help_text='Minutes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('routing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='mrp.routing')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant')),
                ('work_center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mrp.workcenter')),
            ],
        ),
        migrations.CreateModel(
            name='ScrapOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('inventory_item_id', models.IntegerField(blank=True, default=0, null=True)),
                ('component_name', models.CharField(blank=True, max_length=255)),
                ('quantity', models.FloatField(default=1.0)),
                ('reason', models.TextField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('manufacturing_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mrp.manufacturingorder')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancel', 'Cancelled')], default='pending', max_length=20)),
                ('duration_expected', models.FloatField(default=60)),
                ('duration_real', models.FloatField(default=0)),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('date_finished', models.DateTimeField(blank=True, null=True)),
                ('sequence', models.IntegerField(default=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('manufacturing_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='mrp.manufacturingorder')),
                ('operation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mrp.routingoperation')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant')),
                ('work_center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mrp.workcenter')),
            ],
        ),
        migrations.DeleteModel(
            name='BOMComponent',
        ),
    ]
