# Generated by Django 5.2.8 on 2026-08-15 20:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('asset_tag', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('asset_type', models.CharField(choices=[('vehicle', 'Vehicle'), ('equipment', 'Equipment'), ('property', 'Property'), ('machinery', 'Machinery'), ('hardware', 'Hardware'), ('printer', 'Printer'), ('software', 'Software License'), ('cloud', 'Cloud Resource'), ('other', 'Other')], default='hardware', max_length=20)),
                ('make', models.CharField(blank=True, help_text='Manufacturer (e.g. Dell, Apple)', max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('spare', 'In Spare Pool'), ('maintenance', 'Under Maintenance'), ('retired', 'Retired'), ('lost', 'Lost / Stolen')], default='active', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('warranty_expires', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Asset',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Asset Assignment',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('maintenance_type', models.CharField(choices=[('repair', 'Repair'), ('upgrade', 'Upgrade'), ('inspection', 'Inspection'), ('cleaning', 'Cleaning'), ('software_update', 'Software Update'), ('replacement', 'Component Replacement')], max_length=20)),
                ('performed_at', models.DateField()),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_interval_days', models.IntegerField(blank=True, help_text='Days between recurring maintenance', null=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Maintenance Record',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareLicense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('software_name', models.CharField(max_length=255)),
                ('vendor', models.CharField(max_length=255)),
                ('license_key', models.CharField(blank=True, max_length=500)),
                ('license_type', models.CharField(choices=[('perpetual', 'Perpetual'), ('subscription', 'Subscription'), ('open_source', 'Open Source'), ('trial', 'Trial')], default='subscription', max_length=20)),
                ('seats_total', models.IntegerField(default=1)),
                ('seats_used', models.IntegerField(default=0)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('cost_per_seat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Software License',
                'ordering': ['software_name'],
            },
        ),
    ]
