# Generated by Django 5.2.8 on 2026-07-16 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='status',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vin_sn',
        ),
        migrations.RemoveField(
            model_name='vehiclecontract',
            name='cost_frequency',
        ),
        migrations.RemoveField(
            model_name='vehiclecontract',
            name='cost_generated',
        ),
        migrations.RemoveField(
            model_name='vehiclecontract',
            name='insurer_id',
        ),
        migrations.RemoveField(
            model_name='vehiclelog',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='vehiclelog',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='vehiclelog',
            name='odometer_value',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='state',
            field=models.CharField(choices=[('active', 'Active'), ('in_repair', 'In Repair'), ('retired', 'Retired')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='vehiclecontract',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehiclecontract',
            name='insurer',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vehiclecontract',
            name='state',
            field=models.CharField(default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='vehiclelog',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehiclelog',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vehiclelog',
            name='log_type',
            field=models.CharField(choices=[('service', 'Service'), ('odometer', 'Odometer'), ('fuel', 'Fuel')], default='service', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driven_vehicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='odometer',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vehiclecontract',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclecontract',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
