{'name': 'Documents',
    'technical_name': 'documents',
    'version': '1.0.0',
    'category': 'Documents',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'summary': 'Paperless document management (OCR).',
    'description': 'The Document Management module provides comprehensive functionality for managing edms within the ERP '
                   'system. It integrates seamlessly with other core applications.',
    'icon': 'FolderOpen',
    'url': '/admin/documents',
    'depends': ['system'],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],
    'display_name': 'Documents',
    'command_center_section': 'Productivity',
    'sequence': 3,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Documents Tile'}