{'name': 'Field Service',
    'technical_name': 'field_service',
    'version': '1.0.0',
    'category': 'Field Service',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'summary': 'On-site intervention planning.',
    'description': 'The Field Service module provides comprehensive functionality for managing field service within the '
                   'ERP system. It integrates seamlessly with other core applications.',
    'icon': 'MapPin',
    'url': '/admin/field-service',
    'depends': ['system'],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],
    'display_name': 'Field Service',
    'command_center_section': 'Services',
    'sequence': 3,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Field Service Tile'}