{'name': 'Learning',
    'odoo_equivalent': 'eLearning',
    'technical_name': 'learning',
    'version': '1.0.0',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'category': 'eLearning',
    'summary': 'LMS and course management.',
    'description': 'The Elearning module provides comprehensive functionality for managing elearning within the ERP '
                   'system. It integrates seamlessly with other core applications.',
    'icon': 'BookOpen',
    'url': '/admin/learning',
    'depends': ['system', 'website'],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],
    'display_name': 'Learning',
    'command_center_section': 'Website',
    'sequence': 530,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Elearning Tile'}