# Generated by Django 5.2.8 on 2026-05-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysadmin', '0001_initial'),
        ('tenants', '0003_remove_tenant_deleted_at_tenant_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='key',
            field=models.CharField(help_text='Unique identifier for the setting', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='systemsetting',
            unique_together={('tenant', 'key')},
        ),
    ]
