# Generated by Django 5.2.8 on 2026-04-01 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, help_text='Hardware or software vendor (e.g., Cisco, Microsoft)', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_type',
            field=models.CharField(choices=[('instant', 'Instant Download'), ('email', 'Email Delivery'), ('shipping', 'Physical Shipping')], default='instant', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, help_text='L x W x H for shipping', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='license_type',
            field=models.CharField(blank=True, help_text='Perpetual, Subscription, Trial, OEM', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='max_quantity',
            field=models.IntegerField(blank=True, help_text='Maximum B2B order quantity', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='min_quantity',
            field=models.IntegerField(default=1, help_text='Minimum B2B order quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text='Hardware specs (CPU, RAM, Storage)'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.CharField(blank=True, help_text='Distributor (e.g., Ingram Micro, TD SYNNEX)', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_months',
            field=models.IntegerField(default=12, help_text='Warranty period in months'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight for shipping calculations', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
        ),
    ]
