# Generated by Django 5.2.8 on 2026-03-06 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threatintelligence',
            old_name='type',
            new_name='indicator_type',
        ),
    ]
