# Generated by Django 5.2.8 on 2026-03-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('business', 'Business')], default='business', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('prospect', 'Prospect'), ('active', 'Active Customer'), ('subscriber', 'Subscriber'), ('managed_service', 'Managed Service Client'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='prospect', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Primary contact for the client'),
        ),
        migrations.AddField(
            model_name='contact',
            name='role',
            field=models.CharField(blank=True, help_text='e.g. Customer, Decision Maker', max_length=100),
        ),
    ]
