# Generated by Django 5.2.8 on 2026-03-06 20:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0003_phase4_polish'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('hostname', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('device_type', models.CharField(choices=[('workstation', 'Workstation'), ('server', 'Server'), ('firewall', 'Firewall'), ('router', 'Router'), ('switch', 'Switch'), ('mobile', 'Mobile Device'), ('iot', 'IoT Device'), ('other', 'Other')], default='workstation', max_length=20)),
                ('os', models.CharField(blank=True, help_text='e.g. Windows 11, Ubuntu 22.04', max_length=100)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('isolated', 'Isolated'), ('at_risk', 'At Risk'), ('maintenance', 'Maintenance')], default='online', max_length=20)),
                ('agent_version', models.CharField(blank=True, max_length=50)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('risk_score', models.IntegerField(default=0, help_text='0-100 risk score')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Managed Endpoint',
            },
        ),
        migrations.CreateModel(
            name='RemoteSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('active', 'Active'), ('ended', 'Ended'), ('rejected', 'Rejected')], default='requested', max_length=20)),
                ('session_token', models.CharField(blank=True, help_text='Secure one-time token', max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True, help_text='Reason for remote access')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='soc.managedendpoint')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remote_sessions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Remote Session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemMonitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cpu_usage', models.FloatField(default=0.0, help_text='Percentage 0-100')),
                ('ram_usage', models.FloatField(default=0.0, help_text='Percentage 0-100')),
                ('disk_usage', models.FloatField(default=0.0, help_text='Percentage 0-100')),
                ('uptime_seconds', models.BigIntegerField(default=0)),
                ('is_anomalous', models.BooleanField(default=False)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='soc.managedendpoint')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'System Monitor',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspaces', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='NetworkEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('destination_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('source_port', models.IntegerField(blank=True, null=True)),
                ('destination_port', models.IntegerField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, help_text='TCP, UDP, ICMP', max_length=20)),
                ('category', models.CharField(choices=[('intrusion_attempt', 'Intrusion Attempt'), ('port_scan', 'Port Scan'), ('ddos', 'DDoS Activity'), ('lateral_movement', 'Lateral Movement'), ('data_exfiltration', 'Data Exfiltration'), ('anomalous_traffic', 'Anomalous Traffic'), ('normal', 'Normal')], default='normal', max_length=30)),
                ('is_blocked', models.BooleanField(default=False)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='network_events', to='soc.workspace')),
            ],
            options={
                'verbose_name': 'Network Event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='managedendpoint',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='soc.workspace'),
        ),
        migrations.CreateModel(
            name='CloudIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='disconnected', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Encrypted integration config')),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrations', to='soc.workspace')),
            ],
            options={
                'verbose_name': 'Cloud Integration',
            },
        ),
        migrations.CreateModel(
            name='CloudApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(help_text='e.g. Microsoft, Google, AWS', max_length=100)),
                ('app_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('critical', 'Critical'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('users_count', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cloud_apps', to='soc.workspace')),
            ],
            options={
                'verbose_name': 'Cloud App',
            },
        ),
    ]
