# Generated by Django 5.2.8 on 2026-05-22 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_alter_deliverynote_dn_number_and_more'),
        ('store', '0004_partnerrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expense_account',
            field=models.ForeignKey(blank=True, help_text='CoA account to debit on purchase', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_expense_products', to='erp.account'),
        ),
        migrations.AddField(
            model_name='product',
            name='income_account',
            field=models.ForeignKey(blank=True, help_text='CoA account to credit on sale', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_income_products', to='erp.account'),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_products', to='erp.taxconfig'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_label',
            field=models.CharField(default='unit', help_text='e.g. hour, month, unit, license', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('digital', 'Digital Download'), ('physical', 'Physical Hardware'), ('subscription', 'Subscription/Service'), ('service_bundle', 'Service Bundle'), ('service', 'Professional Service')], default='digital', max_length=20),
        ),
    ]
