{'name': 'Equity',
    'technical_name': 'equity',
    'version': '1.0.0',
    'category': 'Accounting',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'summary': 'Equity and cap table management for startups.',
    'description': 'The Equity module provides comprehensive functionality for managing equity within the ERP system. It '
                   'integrates seamlessly with other core applications.',
    'icon': 'TrendingUp',
    'url': '/admin/equity',
    'depends': ['system'],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],
    'display_name': 'Equity',
    'command_center_section': 'Accounting & Finance',
    'sequence': 6,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Equity Tile'}