{'name': 'Payroll',
    'technical_name': 'payroll',
    'version': '1.0.0',
    'category': 'Human Resources',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'summary': 'Payslips and salary rules.',
    'description': 'The Employees Payroll module provides comprehensive functionality for managing hr payroll within the ERP '
                   'system. It integrates seamlessly with other core applications.',
    'icon': 'Banknote',
    'url': '/admin/payroll',
    'depends': ['system', 'employees', 'accounting'],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],
    'display_name': 'Payroll',
    'command_center_section': 'Human Resources',
    'sequence': 760,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Employees Payroll Tile'}