# Generated by Django 5.2.8 on 2026-05-18 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_expense_notes_expense_status'),
        ('store', '0004_partnerrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_invoice_items', to='store.product'),
        ),
    ]
