# Generated by Django 5.2.8 on 2026-05-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_invoice_currency_invoice_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='For quotations: the date the quote expires', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='type',
            field=models.CharField(choices=[('standard', 'Standard Invoice'), ('proforma', 'Proforma Invoice'), ('quotation', 'Quotation / Devis'), ('credit_note', 'Credit Note / Avoir'), ('receipt', 'Payment Receipt')], default='standard', max_length=20),
        ),
    ]
