# Generated by Django 5.2.8 on 2026-05-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_invoice_expiry_date_alter_invoice_type'),
        ('tenants', '0003_remove_tenant_deleted_at_tenant_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynote',
            name='dn_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='deliverynote',
            unique_together={('tenant', 'dn_number')},
        ),
        migrations.DeleteModel(
            name='ProductCatalog',
        ),
    ]
