# Generated by Django 5.2.8 on 2026-07-16 20:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0001_initial'),
        ('tenants', '0003_tenant_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='channelmember',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='channelmember',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='channelmember',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='channelmember',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='channelmember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AddField(
            model_name='channel',
            name='channel_type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('chat', 'Direct Message'), ('livechat', 'LiveChat')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='channel',
            name='members',
            field=models.ManyToManyField(related_name='discuss_channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discuss_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='LiveChatChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('welcome_message', models.TextField(blank=True, default='How can we help you?')),
                ('button_text', models.CharField(default='Chat with us', max_length=50)),
                ('button_color', models.CharField(default='#3b82f6', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant')),
            ],
        ),
    ]
