# Generated by Django 5.2.8 on 2026-07-16 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0002_alter_channelmember_unique_together_and_more'),
        ('website', '0002_landingpage_mediaasset_servicepage_website_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livechatchannel',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livechat_channels', to='website.website'),
        ),
        migrations.DeleteModel(
            name='ChannelMember',
        ),
    ]
