{'name': 'Knowledge',
    'technical_name': 'knowledge',
    'version': '1.0.0',
    'category': 'Website',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'summary': 'Internal Wiki/Notion-style documentation.',
    'description': 'Centralized knowledge base and documentation.',
    'icon': 'BookOpen',
    'url': '/admin/knowledge',
    'depends': ['core'],
    'installable': True,
    'application': True,
    'featured': False,
    'screenshots': [],
    'display_name': 'Knowledge',
    'command_center_section': 'Productivity',
    'sequence': 6,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Knowledge Tile'}