{'name': 'VoIP',
    'technical_name': 'voip',
    'version': '1.0.0',
    'summary': 'Integrated SIP telephony.',
    'description': 'VoIP for BitGuard ERP',
    'category': 'Discuss',
    'author': 'BitGuard',
    'website': 'https://www.bitguard.com',
    'depends': ['core', 'system'],
    'installable': True,
    'application': True,
    'auto_install': False,
    'icon': 'PhoneCall',
    'url': '/admin/voip',
    'screenshots': [],
    'display_name': 'VoIP',
    'command_center_section': 'Productivity',
    'sequence': 8,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Voip Tile'}