{'name': 'SMS Marketing',
    'technical_name': 'sms',
    'display_name': 'SMS Marketing',
    'version': '1.0.0',
    'category': 'SMS',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'summary': 'Text message campaigns.',
    'description': 'Send SMS marketing campaigns.',
    'icon': 'MessageCircle',
    'url': '/admin/sms',
    'depends': ['marketing'],
    'installable': True,
    'application': True,
    'featured': False,
    'screenshots': [],
    'module_type': 'integration',
    'command_center_section': 'Marketing',
    'sequence': 2,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Sms Tile'}