{'name': 'Delivery',
    'technical_name': 'delivery',
    'version': '1.0.0',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'category': 'Inventory',
    'summary': 'Adds shipping methods and carrier integrations (FedEx, UPS) inside the Sales and Inventory apps.',
    'description': 'The Delivery module provides comprehensive functionality for managing delivery within the ERP system. '
                   'It integrates seamlessly with other core applications.',
    'icon': 'Truck',
    'url': '/admin/delivery',
    'depends': ['stock'],
    'installable': True,
    'application': False,
    'featured': True,
    'screenshots': [],
    'display_name': 'Delivery',
    'sequence': 99,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Delivery Tile'}