{'icon': 'Share2',
    'name': 'Social Marketing',
    'version': '1.0',
    'category': 'Marketing',
    'summary': 'Facebook/Twitter/LinkedIn scheduling.',
    'description': 'BitGuard Social module.',
    'depends': ['core'],
    'url': '/admin/social',
    'installable': True,
    'application': True,
    'featured': False,
    'display_name': 'Social',
    'command_center_section': 'Marketing',
    'sequence': 4,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Social Tile'}