{'name': 'Accounting',
    'technical_name': 'accounting',
    'version': '1.0.0',
    'category': 'Accounting',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'summary': 'The master general ledger and reconciliation.',
    'description': 'The Accounting module provides comprehensive functionality for managing accounting within the ERP '
                   'system. It integrates seamlessly with other core applications.',
    'icon': 'PieChart',
    'url': '/admin/accounting',
    'depends': ['system'],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],
    'display_name': 'Accounting',
    'command_center_section': 'Accounting & Finance',
    'sequence': 1,
    'has_settings': True,
    'settings_url': '/admin/settings/accounting',
    'settings_desc': 'Configure settings',
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Accounting Tile'}