# Generated by Django 5.2.8 on 2026-08-20 13:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('model_name', models.CharField(help_text='e.g. crm.Lead, helpdesk.Ticket', max_length=100)),
                ('trigger', models.CharField(choices=[('on_create', 'On Record Creation'), ('on_write', 'On Record Update'), ('on_unlink', 'On Record Deletion'), ('on_stage_set', 'When Stage Is Set To'), ('on_time', 'Based on Time Condition')], max_length=30)),
                ('filter_domain', models.JSONField(blank=True, default=dict)),
                ('action_type', models.CharField(choices=[('update_field', 'Update a Field'), ('send_email', 'Send Email'), ('send_notification', 'Send In-App Notification'), ('create_activity', 'Schedule Activity'), ('call_webhook', 'Call External Webhook')], max_length=30)),
                ('action_data', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Automated Action',
                'verbose_name_plural': 'Automated Actions',
                'db_table': 'automation_automatedaction',
            },
        ),
    ]
