{'name': 'Lunch',
    'technical_name': 'lunch',
    'version': '1.0.0',
    'summary': 'Office meal ordering.',
    'description': 'Lunch for BitGuard ERP',
    'category': 'Human Resources',
    'author': 'BitGuard',
    'website': 'https://www.bitguard.com',
    'depends': ['core', 'system'],
    'installable': True,
    'application': True,
    'auto_install': False,
    'icon': 'Utensils',
    'url': '/admin/lunch',
    'screenshots': [],
    'display_name': 'Lunch',
    'command_center_section': 'Human Resources',
    'sequence': 11,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Lunch Tile'}