# Generated by Django 5.2.8 on 2026-09-16 17:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=500)),
                ('body_html', models.TextField(blank=True)),
                ('body_text', models.TextField(blank=True)),
                ('model', models.CharField(blank=True, help_text='e.g. sale.order â€” applies to this model', max_length=100)),
                ('reply_to', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('lang', models.CharField(blank=True, help_text='e.g. en_US', max_length=10)),
                ('use_default_to', models.BooleanField(default=True)),
                ('partner_to', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Email Template',
                'db_table': 'base_setup_emailtemplate',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IncomingMailServer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(help_text='Account label', max_length=255)),
                ('server_type', models.CharField(choices=[('imap', 'IMAP'), ('pop3', 'POP3')], default='imap', max_length=10)),
                ('server', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=993)),
                ('is_ssl', models.BooleanField(default=True)),
                ('user', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_fetch', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Incoming Mail Server',
                'verbose_name_plural': 'Incoming Mail Servers',
                'db_table': 'base_setup_incomingmailserver',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MailAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('alias_name', models.CharField(max_length=100)),
                ('alias_domain', models.CharField(max_length=255)),
                ('alias_model', models.CharField(blank=True, help_text='e.g. helpdesk.ticket', max_length=255)),
                ('alias_defaults', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.CharField(choices=[('system', 'System'), ('crm', 'CRM'), ('erp', 'ERP'), ('soc', 'SOC'), ('ecommerce', 'ecommerce'), ('billing', 'Billing'), ('hrm', 'HRM'), ('services', 'Services'), ('approvals', 'Approvals'), ('projects', 'Projects')], default='system', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('delivered_in_app', models.BooleanField(default=True)),
                ('delivered_email', models.BooleanField(default=False)),
                ('delivered_sms', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.CharField(choices=[('system', 'System'), ('crm', 'CRM'), ('erp', 'ERP'), ('soc', 'SOC'), ('ecommerce', 'ecommerce'), ('billing', 'Billing'), ('hrm', 'HRM'), ('services', 'Services'), ('approvals', 'Approvals'), ('projects', 'Projects')], max_length=20)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OutgoingMailServer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(help_text='Description / label', max_length=255)),
                ('smtp_host', models.CharField(max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_user', models.CharField(blank=True, max_length=255)),
                ('smtp_password', models.CharField(blank=True, max_length=255)),
                ('smtp_encryption', models.CharField(choices=[('none', 'None'), ('starttls', 'TLS (STARTTLS)'), ('ssl', 'SSL/TLS')], default='starttls', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sequence', models.PositiveIntegerField(default=10, help_text='Priority order â€” lower = higher priority')),
            ],
            options={
                'verbose_name': 'Outgoing Mail Server',
                'verbose_name_plural': 'Outgoing Mail Servers',
                'db_table': 'base_setup_outgoingmailserver',
                'ordering': ['sequence', 'name'],
            },
        ),
    ]
