# Generated by Django 6.0.9 on 2026-10-07 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emailtemplate',
            table=None,
        ),
        migrations.AlterModelTable(
            name='incomingmailserver',
            table=None,
        ),
        migrations.AlterModelTable(
            name='outgoingmailserver',
            table=None,
        ),
    ]
