# Generated by Django 5.2.8 on 2026-08-15 20:26

import apps.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', validators=[apps.core.validators.validate_image_file])),
                ('is_visible', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('internal_reference', models.CharField(blank=True, help_text='Internal reference / SKU', max_length=100)),
                ('barcode', models.CharField(blank=True, help_text='Barcode (EAN, UPC, etc.)', max_length=100, null=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_purchase', models.TextField(blank=True, help_text='Description shown on purchase orders')),
                ('description_sale', models.TextField(blank=True, help_text='Description shown on sale orders / invoices')),
                ('product_type', models.CharField(choices=[('digital', 'Digital Download'), ('physical', 'Physical Hardware'), ('subscription', 'Subscription/Service'), ('service_bundle', 'Service Bundle'), ('service', 'Professional Service')], default='digital', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('sales_ok', models.BooleanField(default=True, help_text='Can be sold')),
                ('purchase_ok', models.BooleanField(default=True, help_text='Can be purchased')),
                ('is_featured', models.BooleanField(default=False)),
                ('can_be_expensed', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stripe_price_id', models.CharField(blank=True, help_text='Stripe Price ID for Checkout', max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='products/', validators=[apps.core.validators.validate_document_file])),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/images/', validators=[apps.core.validators.validate_image_file])),
                ('brand', models.CharField(blank=True, help_text='Hardware or software vendor', max_length=100)),
                ('vendor', models.CharField(blank=True, help_text='Distributor', max_length=100)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dimensions', models.CharField(blank=True, help_text='L x W x H for shipping', max_length=100)),
                ('warranty_months', models.IntegerField(default=12)),
                ('tracking', models.CharField(choices=[('none', 'No Tracking'), ('lot', 'By Lots'), ('serial', 'By Unique Serial Number')], default='none', help_text='Lot/serial tracking method', max_length=20)),
                ('license_type', models.CharField(blank=True, help_text='Perpetual, Subscription, Trial, OEM', max_length=50)),
                ('delivery_type', models.CharField(choices=[('instant', 'Instant Download'), ('email', 'Email Delivery'), ('shipping', 'Physical Shipping')], default='instant', max_length=50)),
                ('min_quantity', models.IntegerField(default=1, help_text='Minimum B2B order quantity')),
                ('max_quantity', models.IntegerField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('features', models.JSONField(blank=True, default=list)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('track_stock', models.BooleanField(default=False)),
                ('is_rental', models.BooleanField(default=False)),
                ('rental_pricing', models.JSONField(blank=True, default=dict, help_text="e.g. {'daily': 50, 'weekly': 200}")),
                ('unit_label', models.CharField(default='unit', help_text='e.g. hour, month, unit, license', max_length=50)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(help_text='e.g. Color, Size, Material', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('value', models.CharField(help_text='e.g. Red, XL, Cotton', max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('rating', models.PositiveIntegerField(default=5, help_text='Rating from 1 to 5')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('comment', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='blue', help_text='Color identifier for UI display', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('price_extra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/variants/', validators=[apps.core.validators.validate_image_file])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['product', 'id'],
            },
        ),
    ]
