# Generated by Django 5.2.8 on 2026-09-28 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_sequence_options_alter_sequence_table_and_more'),
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_as_uom', to='base.uom'),
        ),
        migrations.AddField(
            model_name='product',
            name='uom_po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_as_uom_po', to='base.uom'),
        ),
    ]
