# Generated by Django 5.2.8 on 2026-08-15 20:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=50)),
                ('source', models.CharField(help_text='e.g. Firewall, IDS', max_length=100)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CloudApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(help_text='e.g. Microsoft, Google, AWS', max_length=100)),
                ('app_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('critical', 'Critical'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('users_count', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cloud App',
            },
        ),
        migrations.CreateModel(
            name='CloudIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='disconnected', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Encrypted integration config')),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cloud Integration',
            },
        ),
        migrations.CreateModel(
            name='ComplianceControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('control_id', models.CharField(help_text='e.g. CC6.1, A.9.1', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('compliant', 'Compliant'), ('partial', 'Partial'), ('non_compliant', 'Non-Compliant'), ('na', 'N/A')], default='non_compliant', max_length=20)),
                ('evidence', models.TextField(blank=True, help_text='Evidence notes or document reference')),
                ('last_reviewed', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['control_id'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceFramework',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('framework', models.CharField(choices=[('soc2', 'SOC 2'), ('iso27001', 'ISO 27001'), ('gdpr', 'GDPR'), ('hipaa', 'HIPAA'), ('pci_dss', 'PCI DSS'), ('nist', 'NIST CSF')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('last_assessed', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('mitigated', 'Mitigated'), ('closed', 'Closed')], default='open', max_length=50)),
                ('external_event_id', models.CharField(blank=True, help_text='ID from external SIEM/System', max_length=255, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LogAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('source_system', models.CharField(max_length=100)),
                ('raw_log', models.TextField()),
                ('parsed_data', models.JSONField(blank=True, default=dict)),
                ('flagged_anomalous', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Log Analyses',
            },
        ),
        migrations.CreateModel(
            name='ManagedEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('hostname', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('device_type', models.CharField(choices=[('workstation', 'Workstation'), ('server', 'Server'), ('firewall', 'Firewall'), ('router', 'Router'), ('switch', 'Switch'), ('mobile', 'Mobile Device'), ('iot', 'IoT Device'), ('other', 'Other')], default='workstation', max_length=20)),
                ('os', models.CharField(blank=True, help_text='e.g. Windows 11, Ubuntu 22.04', max_length=100)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('isolated', 'Isolated'), ('at_risk', 'At Risk'), ('maintenance', 'Maintenance')], default='online', max_length=20)),
                ('agent_version', models.CharField(blank=True, max_length=50)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('risk_score', models.IntegerField(default=0, help_text='0-100 risk score')),
            ],
            options={
                'verbose_name': 'Managed Endpoint',
            },
        ),
        migrations.CreateModel(
            name='NetworkEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('destination_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('source_port', models.IntegerField(blank=True, null=True)),
                ('destination_port', models.IntegerField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, help_text='TCP, UDP, ICMP', max_length=20)),
                ('category', models.CharField(choices=[('intrusion_attempt', 'Intrusion Attempt'), ('port_scan', 'Port Scan'), ('ddos', 'DDoS Activity'), ('lateral_movement', 'Lateral Movement'), ('data_exfiltration', 'Data Exfiltration'), ('anomalous_traffic', 'Anomalous Traffic'), ('normal', 'Normal')], default='normal', max_length=30)),
                ('is_blocked', models.BooleanField(default=False)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Network Event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RemoteSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('active', 'Active'), ('ended', 'Ended'), ('rejected', 'Rejected')], default='requested', max_length=20)),
                ('session_token', models.CharField(blank=True, help_text='Secure one-time token', max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True, help_text='Reason for remote access')),
            ],
            options={
                'verbose_name': 'Remote Session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemMonitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('cpu_usage', models.FloatField(default=0.0, help_text='Percentage 0-100')),
                ('ram_usage', models.FloatField(default=0.0, help_text='Percentage 0-100')),
                ('disk_usage', models.FloatField(default=0.0, help_text='Percentage 0-100')),
                ('uptime_seconds', models.BigIntegerField(default=0)),
                ('is_anomalous', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'System Monitor',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreatIntelligence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('indicator', models.CharField(help_text='IP, Domain, File Hash', max_length=255)),
                ('indicator_type', models.CharField(help_text='e.g. IP Address, Malicious URL', max_length=50)),
                ('confidence', models.IntegerField(default=50, help_text='0-100 score')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Threat Intelligence',
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
