# Generated by Django 5.2.8 on 2026-05-17 18:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0005_remove_alert_deleted_at_remove_incident_deleted_at_and_more'),
        ('tenants', '0003_remove_tenant_deleted_at_tenant_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='external_event_id',
            field=models.CharField(blank=True, help_text='ID from external SIEM/System', max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ComplianceFramework',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('framework', models.CharField(choices=[('soc2', 'SOC 2'), ('iso27001', 'ISO 27001'), ('gdpr', 'GDPR'), ('hipaa', 'HIPAA'), ('pci_dss', 'PCI DSS'), ('nist', 'NIST CSF')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('last_assessed', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'framework')},
            },
        ),
        migrations.CreateModel(
            name='ComplianceControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('control_id', models.CharField(help_text='e.g. CC6.1, A.9.1', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('compliant', 'Compliant'), ('partial', 'Partial'), ('non_compliant', 'Non-Compliant'), ('na', 'N/A')], default='non_compliant', max_length=20)),
                ('evidence', models.TextField(blank=True, help_text='Evidence notes or document reference')),
                ('last_reviewed', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_controls', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='soc.complianceframework')),
            ],
            options={
                'ordering': ['control_id'],
                'unique_together': {('framework', 'control_id')},
            },
        ),
    ]
