{'name': 'Reports',
    'odoo_equivalent': 'Reporting',
    'technical_name': 'reports',
    'version': '1.0.0',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'category': 'Technical',
    'summary': 'The PDF/Excel generation engine used by Accounting and Sales.',
    'description': 'The Reports module (technically named reporting) provides HTML/CSS PDF generation for invoices, '
                   'quotes, and delivery notes.',
    'icon': 'FileText',
    'url': '/admin/reports',
    'depends': ['system'],
    'installable': True,
    'application': False,
    'featured': False,
    'screenshots': [],
    'display_name': 'Reports',
    'sequence': 99,
    'has_settings': False,
    'ui_paradigm': 'Hidden UI (Has React Components, but no Command Center Tile)',
    'navigation_path': 'Command Center -> Settings -> Reporting (or embedded in Primary Apps)'}