{'name': 'Consolidation',
    'technical_name': 'consolidation',
    'version': '1.0.0',
    'summary': 'Multi-company financial merging.',
    'description': 'Consolidation for BitGuard ERP',
    'category': 'Accounting',
    'author': 'BitGuard',
    'website': 'https://www.bitguard.com',
    'depends': ['core', 'system'],
    'installable': True,
    'application': True,
    'auto_install': False,
    'icon': 'Layers',
    'url': '/admin/consolidation',
    'screenshots': [],
    'display_name': 'Consolidation',
    'command_center_section': 'Accounting & Finance',
    'sequence': 3,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Consolidation Tile'}