# Generated by Django 5.2.8 on 2026-08-15 20:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('activity_type', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('note', 'Note')], max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('client_type', models.CharField(choices=[('individual', 'Individual'), ('business', 'Business')], default='business', max_length=20)),
                ('status', models.CharField(choices=[('prospect', 'Prospect'), ('active', 'Active Customer'), ('subscriber', 'Subscriber'), ('managed_service', 'Managed Service Client'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='prospect', max_length=20)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(blank=True, help_text='e.g. Decision Maker, Champion', max_length=100)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary contact for the client')),
            ],
        ),
        migrations.CreateModel(
            name='CrmSalesTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('alias_email', models.EmailField(blank=True, help_text='Inbound email alias â€” emails sent here auto-create leads', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sales Team',
                'verbose_name_plural': 'Sales Teams',
            },
        ),
        migrations.CreateModel(
            name='CrmStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('sequence', models.IntegerField(default=10, help_text='Lower = leftmost column in Kanban')),
                ('is_won', models.BooleanField(default=False, help_text='Deals in this stage count as Closed Won')),
                ('is_lost', models.BooleanField(default=False, help_text='Deals in this stage count as Closed Lost')),
                ('fold', models.BooleanField(default=False, help_text='Fold this column in Kanban view by default')),
                ('probability', models.IntegerField(default=0, help_text='Default win probability (%) assigned to deals entering this stage')),
                ('color', models.CharField(default='#3b82f6', help_text='Hex color for Kanban column header', max_length=7)),
                ('requirements', models.TextField(blank=True, help_text='Optional checklist or notes shown to the salesperson for this stage')),
            ],
            options={
                'verbose_name': 'CRM Stage',
                'verbose_name_plural': 'CRM Stages',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='CrmTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#6b7280', max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('probability', models.IntegerField(default=10, help_text='Win probability 0â€“100%')),
                ('priority', models.CharField(choices=[('0', 'Normal'), ('1', 'Low'), ('2', 'High'), ('3', 'Very High')], default='0', max_length=1)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(help_text='Opportunity or lead title', max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(blank=True, help_text='Prospect company name', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(choices=[('website', 'Website'), ('referral', 'Referral'), ('cold_call', 'Cold Call'), ('event', 'Event'), ('social', 'Social Media'), ('partner', 'Partner'), ('ad', 'Advertising'), ('other', 'Other')], default='website', max_length=50)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('lost', 'Lost'), ('converted', 'Converted')], default='new', max_length=50)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, help_text='Estimated deal value if converted', max_digits=12)),
                ('score', models.IntegerField(default=0, help_text='Lead score based on activity and profile')),
                ('probability', models.IntegerField(default=10, help_text='Estimated win probability 0â€“100%')),
                ('priority', models.CharField(choices=[('0', 'Normal'), ('1', 'Low'), ('2', 'High'), ('3', 'Very High')], default='0', max_length=1)),
                ('description', models.TextField(blank=True)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('lost_reason', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LostReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lost Reason',
                'verbose_name_plural': 'Lost Reasons',
                'ordering': ['name'],
            },
        ),
    ]
