# Generated by Django 5.2.8 on 2026-07-16 20:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_initial'),
        ('tenants', '0003_tenant_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='deal',
            name='lead',
            field=models.OneToOneField(blank=True, help_text='The lead this deal was converted from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_deal', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='deal',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='priority',
            field=models.CharField(choices=[('0', 'Normal'), ('1', 'Low'), ('2', 'High'), ('3', 'Very High')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='deal',
            name='probability',
            field=models.IntegerField(default=10, help_text='Win probability 0–100%'),
        ),
        migrations.AddField(
            model_name='lead',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_leads', to='crm.client'),
        ),
        migrations.AddField(
            model_name='lead',
            name='company',
            field=models.CharField(blank=True, help_text='Prospect company name', max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='lead',
            name='expected_close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='lost_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('0', 'Normal'), ('1', 'Low'), ('2', 'High'), ('3', 'Very High')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='lead',
            name='probability',
            field=models.IntegerField(default=10, help_text='Estimated win probability 0–100%'),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('referral', 'Referral'), ('cold_call', 'Cold Call'), ('event', 'Event'), ('social', 'Social Media'), ('partner', 'Partner'), ('ad', 'Advertising'), ('other', 'Other')], default='website', max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_activities', to='crm.client'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_activities', to='crm.deal'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_activities', to='crm.lead'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(blank=True, help_text='e.g. Decision Maker, Champion', max_length=100),
        ),
        migrations.AlterField(
            model_name='deal',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='lead',
            name='score',
            field=models.IntegerField(default=0, help_text='Lead score based on activity and profile'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='title',
            field=models.CharField(help_text='Opportunity or lead title', max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Estimated deal value if converted', max_digits=12),
        ),
        migrations.CreateModel(
            name='CrmSalesTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('alias_email', models.EmailField(blank=True, help_text='Inbound email alias — emails sent here auto-create leads', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_crm_teams', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='crm_teams', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Sales Team',
                'verbose_name_plural': 'Sales Teams',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='crm.crmsalesteam'),
        ),
        migrations.AddField(
            model_name='deal',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.crmsalesteam'),
        ),
        migrations.AddField(
            model_name='lead',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.crmsalesteam'),
        ),
        migrations.CreateModel(
            name='CrmStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('sequence', models.IntegerField(default=10, help_text='Lower = leftmost column in Kanban')),
                ('is_won', models.BooleanField(default=False, help_text='Deals in this stage count as Closed Won')),
                ('is_lost', models.BooleanField(default=False, help_text='Deals in this stage count as Closed Lost')),
                ('fold', models.BooleanField(default=False, help_text='Fold this column in Kanban view by default')),
                ('probability', models.IntegerField(default=0, help_text='Default win probability (%) assigned to deals entering this stage')),
                ('color', models.CharField(default='#3b82f6', help_text='Hex color for Kanban column header', max_length=7)),
                ('requirements', models.TextField(blank=True, help_text='Optional checklist or notes shown to the salesperson for this stage')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'CRM Stage',
                'verbose_name_plural': 'CRM Stages',
                'ordering': ['sequence'],
            },
        ),
        migrations.AlterField(
            model_name='deal',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.crmstage'),
        ),
        migrations.CreateModel(
            name='CrmTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#6b7280', max_length=7)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='deals', to='crm.crmtag'),
        ),
        migrations.AddField(
            model_name='lead',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='leads', to='crm.crmtag'),
        ),
        migrations.CreateModel(
            name='LostReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Lost Reason',
                'verbose_name_plural': 'Lost Reasons',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='lost_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.lostreason'),
        ),
    ]
