with open("backend/apps/core/registry.py", "a") as f:
    f.write("\n\nclass KPIRegistry:\n")
    f.write('    """\n')
    f.write('    Tier-1 Global KPI Registry.\n')
    f.write('    Downstream apps push their metric calculation functions here during AppConfig.ready().\n')
    f.write('    """\n')
    f.write('    def __init__(self):\n')
    f.write('        self._kpi_providers = {}\n\n')
    f.write('    def register(self, app_name, provider_func):\n')
    f.write('        """\n')
    f.write("        Registers a KPI function.\n")
    f.write("        provider_func must accept (tenant=None, date_range='30days') and return a dict.\n")
    f.write('        """\n')
    f.write('        self._kpi_providers[app_name] = provider_func\n\n')
    f.write('    def get_all_providers(self):\n')
    f.write('        return self._kpi_providers\n\n')
    f.write('# Singleton KPI Registry Instance\n')
    f.write('kpi_registry = KPIRegistry()\n')
