# Generated by Django 5.2.8 on 2026-08-15 20:26

import apps.core.validators
import apps.tenants.domain.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(help_text='Subdomain or custom domain', max_length=255, unique=True)),
                ('subscription_plan', models.CharField(default='free', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_modules', models.JSONField(default=apps.tenants.domain.models.default_modules, help_text="List of enabled modules (e.g. ['crm', 'soc'])")),
                ('logo', models.ImageField(blank=True, help_text='Company Logo', null=True, upload_to='tenant_logos/', validators=[apps.core.validators.validate_image_file])),
                ('vat', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('street2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(default='USD', max_length=10)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
            },
        ),
    ]
