# Generated by Django 5.2.8 on 2026-09-29 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='city',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='country',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='state',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='street',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='street2',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='vat',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='zip_code',
        ),
    ]
