# Generated by Django 5.2.8 on 2026-07-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, help_text='Company Logo', null=True, upload_to='tenant_logos/'),
        ),
    ]
