# Generated by Django 5.2.8 on 2026-09-30 19:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_remove_tenant_city_remove_tenant_country_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE users_securitypolicy RENAME TO tenants_securitypolicy;",
                    reverse_sql="ALTER TABLE tenants_securitypolicy RENAME TO users_securitypolicy;"
                ),
            ],
            state_operations=[
                migrations.CreateModel(
            name="SecurityPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "password_complexity",
                    models.CharField(default="high", max_length=20),
                ),
                ("session_timeout", models.IntegerField(default=60)),
                ("mfa_required", models.BooleanField(default=True)),
                ("api_key_rotation", models.IntegerField(default=90)),
                (
                    "ip_whitelist",
                    models.TextField(
                        blank=True, help_text="Comma-separated CIDR ranges"
                    ),
                ),
                ("failed_login_lock", models.IntegerField(default=5)),
                ("lock_duration", models.IntegerField(default=30)),
                ("concurrent_sessions", models.CharField(default="1", max_length=20)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_policy",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
            ]
        )
    ]
