{'name': 'Planning',
    'technical_name': 'planning',
    'version': '1.0.0',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'category': 'Planning',
    'summary': 'Shift and schedule management.',
    'description': 'The Planning module provides comprehensive functionality for managing planning within the ERP system. '
                   'It integrates seamlessly with other core applications.',
    'icon': 'Calendar',
    'url': '/admin/planning',
    'depends': ['system', 'projects', 'hr'],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],
    'display_name': 'Planning',
    'command_center_section': 'Services',
    'sequence': 5,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Planning Tile'}