# Generated by Django 5.2.8 on 2026-08-15 20:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PosConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('receipt_header', models.TextField(blank=True)),
                ('is_restaurant', models.BooleanField(default=False, help_text='Enable Restaurant/Bar features (Floors, Tables)')),
            ],
        ),
        migrations.CreateModel(
            name='PosOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date_order', models.DateTimeField(auto_now_add=True)),
                ('amount_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('state', models.CharField(choices=[('draft', 'New'), ('paid', 'Paid'), ('done', 'Posted'), ('invoiced', 'Invoiced')], default='draft', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PosPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PosSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('start_at', models.DateTimeField(auto_now_add=True)),
                ('stop_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('opening_control', 'Opening Control'), ('opened', 'In Progress'), ('closing_control', 'Closing Control'), ('closed', 'Closed')], default='opening_control', max_length=20)),
                ('cash_register_balance_start', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cash_register_balance_end_real', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantFloor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('background_color', models.CharField(default='rgba(235, 236, 240, 1)', max_length=20)),
                ('sequence', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantPrinter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('printer_type', models.CharField(choices=[('network', 'Network Printer'), ('bluetooth', 'Bluetooth Printer'), ('usb', 'USB Printer')], default='network', max_length=50)),
                ('ip_address', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('seats', models.IntegerField(default=1)),
                ('position_x', models.IntegerField(default=0, help_text='X Coordinate for Floor Plan')),
                ('position_y', models.IntegerField(default=0, help_text='Y Coordinate for Floor Plan')),
                ('width', models.IntegerField(default=50)),
                ('height', models.IntegerField(default=50)),
                ('shape', models.CharField(choices=[('square', 'Square'), ('round', 'Round')], default='square', max_length=20)),
            ],
        ),
    ]
