# Generated by Django 5.2.8 on 2026-07-16 20:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
        ('tenants', '0003_tenant_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posconfig',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='posconfig',
            name='receipt_footer',
        ),
        migrations.RemoveField(
            model_name='posorder',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='posorder',
            name='amount_return',
        ),
        migrations.RemoveField(
            model_name='posorder',
            name='amount_tax',
        ),
        migrations.RemoveField(
            model_name='posorder',
            name='client',
        ),
        migrations.RemoveField(
            model_name='posorder',
            name='receipt_number',
        ),
        migrations.RemoveField(
            model_name='posorder',
            name='status',
        ),
        migrations.RemoveField(
            model_name='posorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pospayment',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='possession',
            name='status',
        ),
        migrations.AddField(
            model_name='posconfig',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='posconfig',
            name='is_restaurant',
            field=models.BooleanField(default=False, help_text='Enable Restaurant/Bar features (Floors, Tables)'),
        ),
        migrations.AddField(
            model_name='posorder',
            name='state',
            field=models.CharField(choices=[('draft', 'New'), ('paid', 'Paid'), ('done', 'Posted'), ('invoiced', 'Invoiced')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='possession',
            name='state',
            field=models.CharField(choices=[('opening_control', 'Opening Control'), ('opened', 'In Progress'), ('closing_control', 'Closing Control'), ('closed', 'Closed')], default='opening_control', max_length=20),
        ),
        migrations.AlterField(
            model_name='posconfig',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='posorder',
            name='amount_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pospayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='possession',
            name='cash_register_balance_end_real',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='possession',
            name='cash_register_balance_start',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='possession',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.posconfig'),
        ),
        migrations.CreateModel(
            name='RestaurantFloor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('background_color', models.CharField(default='rgba(235, 236, 240, 1)', max_length=20)),
                ('sequence', models.IntegerField(default=10)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='pos.posconfig')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantPrinter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('printer_type', models.CharField(choices=[('network', 'Network Printer'), ('bluetooth', 'Bluetooth Printer'), ('usb', 'USB Printer')], default='network', max_length=50)),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='pos.posconfig')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('seats', models.IntegerField(default=1)),
                ('position_x', models.IntegerField(default=0, help_text='X Coordinate for Floor Plan')),
                ('position_y', models.IntegerField(default=0, help_text='Y Coordinate for Floor Plan')),
                ('width', models.IntegerField(default=50)),
                ('height', models.IntegerField(default=50)),
                ('shape', models.CharField(choices=[('square', 'Square'), ('round', 'Round')], default='square', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='pos.restaurantfloor')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant')),
            ],
        ),
        migrations.DeleteModel(
            name='POSOrderLine',
        ),
    ]
