{'name': 'Blog',
    'technical_name': 'blog',
    'version': '1.0.0',
    'category': 'Website',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'summary': 'Content marketing.',
    'description': 'The Blog module provides comprehensive functionality for managing blog within the ERP system. It '
                   'integrates seamlessly with other core applications.',
    'icon': 'FileText',
    'url': '/admin/blog',
    'depends': ['system'],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],
    'display_name': 'Blog',
    'command_center_section': 'Website',
    'sequence': 5,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Blog Tile'}