{'name': 'ESG Reporting',
    'technical_name': 'esg',
    'version': '1.0.0',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'category': 'Accounting',
    'summary': 'Track environmental, social, and governance metrics.',
    'description': 'The Esg module provides comprehensive functionality for managing esg within the ERP system. It '
                   'integrates seamlessly with other core applications.',
    'icon': 'Leaf',
    'url': '/admin/esg',
    'depends': ['system'],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],
    'display_name': 'ESG Reporting',
    'command_center_section': 'Human Resources',
    'sequence': 5,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Esg Tile'}