{'name': 'Production',
    'odoo_equivalent': 'Shop Floor',
    'technical_name': 'production',
    'version': '1.0.0',
    'category': 'Manufacturing',
    'author': 'BitGuard',
    'display_name': 'Production',
    'summary': 'Shop Floor module',
    'description': 'Core functionality for Shop Floor',
    'icon': 'Box',
    'url': '/admin/production',
    'depends': ['system'],
    'installable': True,
    'application': True,
    'command_center_section': 'Manufacturing',
    'sequence': 420}