# Generated by Django 5.2.8 on 2026-04-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_knowledgearticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='SLA based resolution deadline', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_converted_to_kb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='related_articles',
            field=models.ManyToManyField(blank=True, related_name='linked_tickets', to='support.knowledgearticle'),
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
