# Generated by Django 5.2.8 on 2026-04-29 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsm', '0002_changerequest_tenant_changetask_tenant_and_more'),
        ('support', '0003_ticket_due_date_ticket_is_converted_to_kb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='itsm.problem'),
        ),
    ]
