{'name': 'Studio',
    'technical_name': 'studio',
    'version': '1.0.0',
    'summary': 'Studio Module',
    'description': 'Studio for BitGuard ERP',
    'category': 'Technical',
    'author': 'BitGuard',
    'website': 'https://www.bitguard.com',
    'depends': ['core', 'system'],
    'installable': True,
    'application': True,
    'auto_install': False,
    'icon': 'PenTool',
    'url': '/admin/studio',
    'screenshots': [],
    'display_name': 'Studio',
    'command_center_section': 'Administration',
    'sequence': 99,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Studio Tile'}