{'name': 'WhatsApp',
    'technical_name': 'whatsapp',
    'display_name': 'WhatsApp',
    'version': '1.0.0',
    'category': 'Discuss',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'summary': 'Communicate with clients via WhatsApp.',
    'description': 'Communicate with clients via WhatsApp.',
    'icon': 'MessageCircle',
    'url': '/admin/whatsapp',
    'depends': ['core'],
    'installable': True,
    'application': True,
    'featured': False,
    'screenshots': [],
    'module_type': 'integration',
    'command_center_section': 'Discuss',
    'command_center_order': 10,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Settings -> Integrations (or Webhook Triggered)',
    'sequence': 840,
    'has_settings': True,
    'settings_url': '/admin/settings/whatsapp'
}