{'name': 'Approvals',
    'technical_name': 'approvals',
    'version': '1.0.0',
    'category': 'Technical',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'summary': 'Custom request validation flows.',
    'description': 'The Approvals module provides comprehensive functionality for managing approvals within the ERP '
                   'system. It integrates seamlessly with other core applications.',
    'icon': 'CheckSquare',
    'url': '/admin/approvals',
    'depends': ['system'],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],
    'display_name': 'Approvals',
    'sequence': 5,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Approvals Tile',
    'command_center_section': 'Productivity'}