{'name': 'Tenants',
    'technical_name': 'tenants',
    'version': '1.0.0',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'category': 'Technical',
    'summary': 'Multi-SaaS isolation and data segregation.',
    'description': 'The Tenants module provides comprehensive functionality for managing tenants within the ERP system. '
                   'It integrates seamlessly with other core applications.',
    'icon': 'Building2',
    'url': '/admin/tenants',
    'depends': ['system'],
    'installable': True,
    'application': False,
    'featured': True,
    'screenshots': [],
    'display_name': 'Multi-Tenancy',
    'has_settings': False,
    'ui_paradigm': 'Headless Core (Pure Python Backend, No React UI)',
    'navigation_path': 'Command Center -> Settings -> Companies (Super Admin Only)',
    'sequence': 999}