{'name': 'Inventory',
    'technical_name': 'stock',
    'version': '1.0.0',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'category': 'Inventory',
    'summary': 'Warehouse management, routing, and stock valuation.',
    'description': 'The Inventory module provides comprehensive functionality for managing stock within the ERP system. '
                   'It integrates seamlessly with other core applications.',
    'icon': 'Box',
    'url': '/admin/stock',
    'depends': ['system', 'purchase'],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],
    'display_name': 'Inventory',
    'command_center_section': 'Inventory',
    'sequence': 1,
    'has_settings': True,
    'settings_url': '/admin/settings/stock',
    'settings_desc': 'Configure settings',
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Stock Tile'}