{'name': 'Frontdesk',
    'technical_name': 'frontdesk',
    'version': '1.0.0',
    'category': 'Human Resources',
    'author': 'BitGuard',
    'summary': 'Frontdesk module',
    'description': 'Core functionality for Frontdesk',
    'icon': 'Box',
    'url': '/admin/frontdesk',
    'depends': ['system'],
    'installable': True,
    'application': True,
    'command_center_section': 'Human Resources',
    'sequence': 5}