{
    'name': 'Project',
    'technical_name': 'projects',
    'version': '1.0.0',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'category': 'Project',
    'summary': 'Project management with tasks, milestones, Gantt, and Kanban.',
    'description': 'The Project Portfolio module provides comprehensive functionality for managing projects within the ERP system. It integrates seamlessly with other core applications.',
    'icon': 'FolderKanban',
    'url': '/admin/projects',
    'depends': ['system', 'crm'],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],

    'display_name': 'Project',
    'command_center_section': 'Services',
    'sequence': 1,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Projects Tile',
}
