{'name': 'Portal',
    'technical_name': 'portal',
    'version': '1.0.0',
    'category': 'Technical',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'summary': 'Powers the external customer account pages (`/my`). Does not have an admin dashboard tile.',
    'description': 'The Portal module provides comprehensive functionality for managing portal within the ERP system. It '
                   'integrates seamlessly with other core applications.',
    'icon': 'Globe',
    'url': '/admin/portal',
    'depends': ['system'],
    'installable': True,
    'application': False,
    'featured': True,
    'screenshots': [],
    'display_name': 'Portal',
    'sequence': 99,
    'has_settings': False,
    'ui_paradigm': 'Hidden UI (Has React Components, but no Command Center Tile)',
    'navigation_path': 'Customer Gateway -> /my (External Users)'}