# Generated by Django 5.2.8 on 2026-06-16 20:56

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='Overall quote discount percentage', max_digits=5)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Quote',
            },
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Quote Line',
            },
        ),
        migrations.CreateModel(
            name='ServiceContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('contract_type', models.CharField(choices=[('msp', 'Managed Service (MSP)'), ('retainer', 'Retainer'), ('project', 'Project-based'), ('support', 'Support Contract'), ('saas', 'SaaS License')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('pending_renewal', 'Pending Renewal'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='draft', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('monthly_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('auto_renew', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Service Contract',
            },
        ),
        migrations.CreateModel(
            name='SLABreach',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('ticket_id', models.UUIDField(blank=True, help_text='UUID of the Support Ticket', null=True)),
                ('breach_type', models.CharField(choices=[('first_response', 'First Response Exceeded'), ('resolution', 'Resolution Time Exceeded'), ('uptime', 'Uptime SLA Violated')], max_length=20)),
                ('breached_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged', models.BooleanField(default=False)),
                ('resolution_note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'SLA Breach',
            },
        ),
        migrations.CreateModel(
            name='SLATier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('first_response_hours', models.IntegerField(help_text='Max hours to first response')),
                ('resolution_hours', models.IntegerField(help_text='Max hours to resolution')),
                ('uptime_percent', models.DecimalField(decimal_places=2, default=99.9, help_text='Guaranteed uptime (e.g. 99.9)', max_digits=5)),
                ('coverage', models.CharField(choices=[('business_hours', 'Business Hours (8x5)'), ('extended', 'Extended (12x5)'), ('always_on', '24x7')], default='business_hours', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
