# Generated by Django 5.2.8 on 2026-07-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecontract',
            name='contract_type',
            field=models.CharField(choices=[('msp', 'Managed Service (MSP)'), ('retainer', 'Retainer'), ('project', 'Project-based'), ('helpdesk', 'Support Contract'), ('saas', 'SaaS License')], max_length=20),
        ),
    ]
