{
    'name': 'Timesheets',
    'technical_name': 'timesheets',
    'version': '1.0.0',
    'category': 'Timesheets',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'summary': 'Track time spent on tasks and projects.',
    'description': 'Track time spent on tasks and projects.',
    'icon': 'Clock',
    'url': '/admin/timesheets',
    'depends': ['core'],
    'installable': True,
    'application': True,
    'featured': False,
    'screenshots': [],

    'display_name': 'Timesheets',
    'command_center_section': 'Services',
    'sequence': 2,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Timesheets Tile',
}
