{'name': 'Invoicing',
    'technical_name': 'invoicing',
    'version': '1.0.0',
    'summary': 'Customer invoices and vendor bills (Sub-set of Accounting).',
    'description': 'Invoicing for BitGuard ERP',
    'category': 'Accounting',
    'author': 'BitGuard',
    'website': 'https://www.bitguard.com',
    'depends': ['core', 'system'],
    'installable': True,
    'application': True,
    'auto_install': False,
    'icon': 'FileText',
    'url': '/admin/invoicing',
    'screenshots': [],
    'display_name': 'Invoicing',
    'command_center_section': 'Accounting & Finance',
    'sequence': 2,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Invoicing Tile'}