{'name': 'Shipping',
    'odoo_equivalent': 'Delivery',
    'technical_name': 'shipping',
    'version': '1.0.0',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'category': 'Inventory',
    'summary': 'Adds shipping methods and carrier integrations (FedEx, UPS) inside the Sales and Inventory apps.',
    'description': 'The Delivery module provides comprehensive functionality for managing delivery within the ERP system. '
                   'It integrates seamlessly with other core applications.',
    'icon': 'Truck',
    'url': '/admin/shipping',
    'depends': ['inventory'],
    'installable': True,
    'application': False,
    'featured': True,
    'screenshots': [],
    'display_name': 'Shipping',
    'sequence': 99,
    'has_settings': False,
    'ui_paradigm': 'Embedded UI (No standalone Command Center tile — embedded within Inventory and Sales)',
    'navigation_path': 'Embedded within Inventory and Sales apps'}