{'name': 'Attendances',
    'technical_name': 'hr_attendance',
    'version': '1.0.0',
    'category': 'Human Resources',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'summary': 'Check-in/Check-out clock.',
    'description': 'The Hr Attendance module provides comprehensive functionality for managing hr attendance within the '
                   'ERP system. It integrates seamlessly with other core applications.',
    'icon': 'Clock',
    'url': '/admin/hr-attendance',
    'depends': ['system', 'hr'],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],
    'display_name': 'Attendances',
    'command_center_section': 'Human Resources',
    'sequence': 4,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Hr Attendance Tile'}