{'name': 'Expenses',
    'technical_name': 'expenses',
    'version': '1.0.0',
    'author': 'BitGuard',
    'website': 'https://bitguard.io',
    'license': 'LGPL-3',
    'category': 'Human Resources',
    'summary': 'Employee reimbursements.',
    'description': 'The Employees Expense module provides comprehensive functionality for managing hr expense within the ERP '
                   'system. It integrates seamlessly with other core applications.',
    'icon': 'Receipt',
    'url': '/admin/expenses',
    'depends': ['system', 'employees', 'accounting'],
    'installable': True,
    'application': True,
    'featured': True,
    'screenshots': [],
    'display_name': 'Expenses',
    'command_center_section': 'Accounting',
    'sequence': 280,
    'has_settings': False,
    'ui_paradigm': 'Primary Application (Has Dashboard/Command Center Tile)',
    'navigation_path': 'Command Center -> Employees Expense Tile'}